### ISSUE TITLE
[cdk-pipelines] Cross Account CodePipeline IAM roles not configured correctly to pull from Code Commit 

### ISSUE THREAD

**Issue by captainrandom** [aws/aws-cdk#10420]
When I try to read from code commit cross account, IAM roles are configured incorrectly. I need you to either support this use case or show me how to do it.

Below is code which creates a role that assumes a cross-account role that has permissions to pull from the code commit repo (also cross-account). I hand this role and the reference to the repo to the CodeCommitSourceAction on the pipeline. But when I look at the roles that are created and associated with the pipeline, it directly allows the cross-account repo instead of trying to assume the role (created below) which assumes the cross-account role which has access to the code commit repo.

Let me draw this out:

cross account boundary = |

(what should happen)
pipeline -> CodeCommitSourceAction -> (should assume role being created below) -> | cross account role (has access to) -> code commit repo

(what actually happens)
pipeline -> CodeCommitSourceAction -> pipeline role -> source pipeline role (direct access) -> | code commit repo

```javascript

const sourceRepo = Repository.fromRepositoryArn(
            this,
            'source-git-repo',
            "arn:aws:codecommit:<some-region>:<insert-cross-account-here>:some-repo"
        );
let sourceReadRole = new Role(this, this.stackName + '-src-read-role',
            {
                assumedBy: new ServicePrincipal('codepipeline.amazonaws.com'),
                inlinePolicies: {
                    assume_cross_account_repo_role: new PolicyDocument({
                        statements: [
                            new PolicyStatement({
                                resources: [
                                    '<cross-account-role-arn-here>'
                                ],
                                actions: [
                                    'sts:AssumeRole'
                                ]
                            })
                        ]
                    })
                }
            });
        
        const pipeline = new CdkPipeline(this, 'CodePipeline', {
            // The pipeline name
            pipelineName: 'my-pipeline',
            cloudAssemblyArtifact,

            sourceAction: new CodeCommitSourceAction(
                {
                    actionName: 'CodeCommit',
                    repository: sourceRepo,
                    branch: 'some-branch',
                    output: sourceArtifact,
                    role: sourceReadRole
                },
            ),

            synthAction: SimpleSynthAction.standardNpmSynth({
                sourceArtifact,
                cloudAssemblyArtifact,

                // TODO: clean up these comments once I have these working properly.
                // Use this if you need a build step (if you're not using ts-node
                // or if you have TypeScript Lambdas that need to be compiled).
                buildCommand: 'npm run test',
            }),

            cdkCliVersion: '1.63.0'
        });
```

### Use Case

It is best practice to separate your resources into separate accounts thus code pipeline needs to read codecommit cross-account.

### Proposed Solution

I don't know of a full workaround, but my proposed solution would most likely be, on the auto-generated code pipeline source code commit role, just assume the role passed to the CodeCommitSourceAction (assuming there is one).

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @captainrandom ,

thanks for opening the issue. I think you misunderstood how a CodePipeline executes 🙂 . It goes like this:

1. The Pipeline's Role is assumed by the CodePipeline service.
2. The Role of the Action is assumed.
3. The Action executes.

So, in your example, you need to pass into `CodeCommitSourceAction` the Role from the Repository account, _not_ the Role from the Pipeline's account that has permissions to assume a Role from the Repository account.

Hope that clears things up!

Thanks,
Adam

**Comment by captainrandom** [comment]
## Role assuming problem
I added the following code:

```typescript
let crossAccountSourceReadRole = Role.fromRoleArn(
            this,
            'cross-acct-source-read-role',
            'arn:aws:iam::<cross acct id>:role/<cross account code commit role name here>'
        );
```

Then I assigned the `crossAccountSourceReadRole` variable to the `role` on `CodeCommitSourceAction` and it deployed with no changes. Then, I proceeded to delete the stack and re-create it just to be sure I didn't screw anything up. And it still gives me a permission error. Keep in mind that the above role is never assumed by the pipeline role or the auto-generated SourceCodeCommit Role even when I set it on the Action (which is the problem).

## Separate Problem
I just started trying to add permissions blindly until I got a working solution (then curtail later). I started manually adding permissions to each of the roles that allowing it to assume the cross-account role on each of the pipeline roles starting with the auto-generated SourceCodeCommit Role and then moving up to the root code pipeline role (at the root role was when I finally got a different result something other than a permissions error). See the attached image for the other error I got after assuming the cross-account role on the pipeline's Role. This is weird even though I've specified the full arn for the repo. I would appear that the `CodeCommitSourceAction` is looking at the pipeline account instead of the code commit account.

![code-pipeline-cross-account-read-git](https://user-images.githubusercontent.com/13500774/93638033-74a64900-f9ab-11ea-8166-ae3122e09b9e.png)

**Comment by skinny85** [comment]
is the account ID where the CodeCommit repository exist the same as `<cross acct id>` in this code:

```ts
let crossAccountSourceReadRole = Role.fromRoleArn(
            this,
            'cross-acct-source-read-role',
            'arn:aws:iam::<cross acct id>:role/<cross account code commit role name here>'
        );
```

?

**Comment by captainrandom** [comment]
Sorry, I'll try to keep it code-commit account id and code pipeline account id from now on. Yes, the `<cross acct id>` is indeed the account containing the code commit repo.

**Comment by skinny85** [comment]
Ok. Then:

1) Make sure the name you use in the code (`<cross account code commit role name here>`) is indeed the name of an existing Role
2) Make sure that Role allows to be assumed from the pipeline account

You mentioned you got a permissions error... what was it?

**Comment by captainrandom** [comment]
1. It is the same
2. The trust relationship whitelists the pipeline account. Currently, the role in the code commit account is being used in other code pipelines in the pipeline account.

Here is the error paraphrased:
```
The service role or action role doesn’t have the permissions required to access the AWS CodeCommit repository named <repo name>. Update the IAM role permissions, and then try again. Error: User: <auto-generated CodePipelineSourceCodeCommit role> is not authorized to perform: codecommit:GetBranch on resource: arn:aws:codecommit:<region>:<pipeline account id>:<code commit repo name>
```

So, two things:

1. auto-generated CodePipelineSourceCodeCommit role adds the correct resource (code commit repo with the correct the code commit repo account id), but does not assume the `crossAccountSourceReadRole` role. 
2. When the error message above says `not authorized to perform: codecommit:GetBranch on resource: arn:aws:codecommit:<region>:<pipeline account id>:<code commit repo name>`, take notice that code commit repo it is trying to reference is in the wrong account. It is trying to reference the *pipeline account*, when the code commit repo is in the *code commit account*

**Comment by skinny85** [comment]
Sorry, I don't follow. The _existing_ Role that you're importing:

```ts
let crossAccountSourceReadRole = Role.fromRoleArn(
            this,
            'cross-acct-source-read-role',
            'arn:aws:iam::<cross acct id>:role/<cross account code commit role name here>'
        );
```

is the one that needs those CodeCommit permissions - I don't think there's anything the CDK can you do here.

> auto-generated CodePipelineSourceCodeCommit role adds the correct resource (code commit repo with the correct the code commit repo account id), but does not assume the crossAccountSourceReadRole role.

Of course, because the AsusmeRole permissions need to be on the pipeline Role, not on the action Role. The action Role is the one being assumed, it doesn't do any assuming after that.

The wrong account ID is probably because

**Comment by captainrandom** [comment]
No. CDK can do something about this because there exists a set of permissions that will allow this to work and cdk is the main blocker here.

The only way to access a code commit repo from the pipeline account is to assume a role in the code commit account, which does have access to code commit. 

The `crossAccountSourceReadRole` role is in the code commit account and has access to code commit. I pass the `crossAccountSourceReadRole` role to the action (in cdk code), but it is NOT being assumed by the pipeline role PERIOD. Since I don't have access to either the pipeline role or the auto-generated CodePipelineSourceCodeCommit role (which seems to be assumed when running the `CodeCommitSourceAction`), it means that cdk does not give me an option to make this work.

Either you need to have the codepipeline role assume the `crossAccountSourceReadRole` or the auto-generated CodePipelineSourceCodeCommit could just assume the `crossAccountSourceReadRole`.

**Comment by skinny85** [comment]
Sorry, but I'm still not following. If you pass `crossAccountSourceReadRole` to the `CodeCommitSourceAction` in the `role` property, there will be on auto-generated `CodePipelineSourceCodeCommit` Role. Is that not the behavior that you see (so, you pass `crossAccountSourceReadRole` to `CodeCommitSourceAction` in the `role` property, but that is ignored, and a new Role is generated and used for the CodeCommit source action?)?

Thanks,
Adam

**Comment by captainrandom** [comment]
Yes, the `role` property is ignored and a new role is generated. This is seen when I change the role property on the `CodeCommitSourceAction` (only code change) and proceed to deploy the pipeline stack, I am confronted with the following message: "deployed with no changes".

**Comment by skinny85** [comment]
Hey @captainrandom ,

I just tried myself, and I can't reproduce your problem.

First I deployed this super simple Stack containing the pipeline:

```ts
import * as cdk from '@aws-cdk/core';
import * as pipelines from '@aws-cdk/pipelines';
import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as codecommit from '@aws-cdk/aws-codecommit';
import * as cpactions from '@aws-cdk/aws-codepipeline-actions';

export class PipelineStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const cloudAssemblyArtifact = new codepipeline.Artifact();
    const sourceArtifact = new codepipeline.Artifact();
    const pipeline = new pipelines.CdkPipeline(this, 'CodePipeline', {
      pipelineName: 'cross-account-sources-roles-cdkpipelines-question',
      cloudAssemblyArtifact: cloudAssemblyArtifact,

      sourceAction: new cpactions.CodeCommitSourceAction({
        actionName: 'CodeCommit',
        repository: codecommit.Repository.fromRepositoryName(this, 'Repo', 'sample-lambda-cdk-ap'),
        output: sourceArtifact,
      }),
      synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        subdirectory: 'cdk',
      }),
    });
  }
}
```

Then, I tried a very simple change: I just added an imported Role, and passed it to `CodeCommitSourceAction`. Like this:

```ts
    const myRole = iam.Role.fromRoleArn(this, 'Role',
        'arn:aws:iam::123456789012-id:role/my-awesome-role');

     // ...

      sourceAction: new cpactions.CodeCommitSourceAction({
        actionName: 'CodeCommit',
        repository: codecommit.Repository.fromRepositoryName(this, 'Repo', 'sample-lambda-cdk-ap'),
        output: sourceArtifact,
        role: myRole,
      }),

      // ...
```

Everything stayed exactly the same.

`cdk diff` shows (excerpt):

```
Resources
[-] AWS::IAM::Role CodePipelineSourceCodeCommitCodePipelineActionRoleA7B08812 destroy
[-] AWS::IAM::Policy CodePipelineSourceCodeCommitCodePipelineActionRoleDefaultPolicy1CF12CDB destroy

[~] AWS::CodePipeline::Pipeline CodePipeline/Pipeline CodePipeline87CD40FF 
 └─ [~] Stages
     └─ @@ -19,12 +19,7 @@
        [ ]         "Name": "Artifact_Source_CodeCommit"
        [ ]       }
        [ ]     ],
        [-]     "RoleArn": {
        [-]       "Fn::GetAtt": [
        [-]         "CodePipelineSourceCodeCommitCodePipelineActionRoleA7B08812",
        [-]         "Arn"
        [-]       ]
        [-]     },
        [+]     "RoleArn": "arn:aws:iam::123456789012-id:role/my-awesome-role",
        [ ]     "RunOrder": 1
        [ ]   }
        [ ] ],
```

Which is exactly what I expected (the previously auto-generated Role is now gone, and the pipeline configuration now references the imported Role).

Perhaps you didn't `git push` your changes, and your self-mutation Stage overrode the changes you made locally...?

Anyway. If you can't get it to work, maybe start over from my above code, and see if you can get it to work that way.

Thanks,
Adam

**Comment by captainrandom** [comment]
I literally copy-pasted your code and am still having the same above issues.

**Comment by skinny85** [comment]
Which version of `@aws-cdk/pipelines` do you depend on?

**Comment by captainrandom** [comment]
I am using `@aws-cdk/pipelines` version `1.63.0`. Below I have listed the `package.json` file for your viewing pleasure:

```json
{
  "name": "ci_pipeline_test",
  "version": "0.1.0",
  "bin": {
    "ci_pipeline_test": "bin/ci_pipeline_test.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assert": "1.63.0",
    "@types/jest": "^26.0.14",
    "@types/node": "14.11.2",
    "jest": "^26.4.2",
    "ts-jest": "^26.4.0"
  },
  "dependencies": {
    "@aws-cdk/aws-autoscaling": "^1.63.0",
    "@aws-cdk/aws-ec2": "^1.63.0",
    "@aws-cdk/aws-ecr": "^1.63.0",
    "@aws-cdk/aws-ecs": "^1.63.0",
    "@aws-cdk/aws-ecs-patterns": "^1.63.0",
    "@aws-cdk/aws-eks": "^1.63.0",
    "@aws-cdk/aws-iam": "^1.63.0",
    "@aws-cdk/aws-kms": "^1.63.0",
    "@aws-cdk/core": "^1.63.0",
    "@aws-cdk/pipelines": "^1.63.0",
    "aws-cdk": "1.63.0",
    "source-map-support": "^0.5.19",
    "ts-node": "^9.0.0",
    "typescript": "~4.0.3"
  }
}
```

**Comment by skinny85** [comment]
Then I don't know what to tell you. If you want, you ca publish your code to some public Git repository, and I'll take a look.

But I'm pretty sure the code works like I verified, so I don't think there's much I can do here.

**Comment by nishitjain13** [comment]
Hi @captainrandom , I am facing a similar issue, was your issue resolved? If yes, then could you let us know what changes you made.

**Comment by mounir-futurefacts** [comment]
Hi @skinny85, I am in a current situation: 

- setting a a cdk pipeline in account B, with as sourceAction a codecommit repository in account A
- created a role manually in account A with a trust policy to account B for readaccess to the codecommit repo
- importing this role in the pipeline stack and passing it as the role in CodeCommitSourceAction

This all works, BUT the pipeline can now still not build. I get the error:

```
Insufficient permissions
The service role or action role doesn’t have the permissions required to access the Amazon S3 bucket named <artifacts-bucket-of-the-pipeline-in-account-B>. Update the IAM role permissions, and then try again. Error: Amazon S3:AccessDenied:Access Denied
```

I understand that this is not a bug, but perhaps you do know how the cdk pipelines module can be used in such a case to succesfully build from a codecommit repo in a different account. Could I for example not add an additional auto-generated policy to the CodeCommitSourceAction?

**Comment by skinny85** [comment]
@mounir-futurefacts what version of the CDK you're using? Can you show me the contents of your `cdk.json` file?

I think I have a suspicion why you're running into problems.

**Comment by mounir-futurefacts** [comment]
Hi @skinny85, I am using version 1.75.0. My cdk.json looks like this:

```
{
  "app": "python3 app.py",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/core:newStyleStackSynthesis": "true"
  }
}
```

I actually dug a little deeper in the problem, there has been an official blog post on it as well [here](https://aws.amazon.com/blogs/devops/aws-building-a-secure-cross-account-continuous-delivery-pipeline/) that helped me on the right track. In the end I needed to perform the following steps to make the pipeline work (that is, a pipeline in account B, triggered by a repo in account A):

1). manually create a role in account A with a trust relationship to account B
2). deploying the pipeline in account B, using the role from account A as the role in *CodeCommitSourceAction* 
3). initially this will error as the role has no rights to write to the artifacts bucket that is initally created with the pipeline stack (and also the KMS key)
4). add these additional policies
5). set up event rule forwarding from account A to B for the codecommit repo in order to trigger the pipeline

So, quite some steps to make this work (more importantly, manual steps). Any idea on how to make this process more automated?

**Comment by skinny85** [comment]
Yes. Simply import the the Repository into a CDK Stack that has the `env` property set to account A. Then, just pass that `repository` object to the `CodeCommitSourceAction` in the Pipeline's Stack in account B.

The CDK will handle the rest, no manual steps required 🙂.

**Comment by mounir-futurefacts** [comment]
Oh wow, that sounds awesomely simple. I'll try it first thing tomorrow and let you know if it worked, thanks :)

**Comment by mounir-futurefacts** [comment]
Hi @skinny85, I have not been able to figure this out yet. Could you be a little more specific about the steps to take? In my app.py I create a stack with a pipeline in account B. This stack should get the repository object from some other stack, you mentioned? In that case, which stack should this be (note that I am not deploying anything to account A (= repo account) at this point)

**Comment by skinny85** [comment]
@mounir-futurefacts I mean something like this:

```ts
import * as cdk from '@aws-cdk/core';
import * as codebuild from '@aws-cdk/aws-codebuild';
import * as codecommit from '@aws-cdk/aws-codecommit';
import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as codepipeline_actions from '@aws-cdk/aws-codepipeline-actions';

const app = new cdk.App();

const repoStack = new cdk.Stack(app, 'RepoStack', {
    env: { account: 'A', region: 'my-region' },
});
const repo = codecommit.Repository.fromRepositoryName(repoStack, 'MyRepo', 'my-repo');

const pipelineStack = new cdk.Stack(app, 'PipelineStack', {
    env: { account: 'B', region: 'my-region' },
});
const pipeline = new codepipeline.Pipeline(pipelineStack, 'Pipeline');
const sourceOutput = new codepipeline.Artifact();
pipeline.addStage({
    stageName: 'Source',
    actions: [
        new codepipeline_actions.CodeCommitSourceAction({
            actionName: 'Source',
            repository: repo,
            output: sourceOutput,
        }),
    ],
});
// more Stages below...
```

**Comment by mounir-futurefacts** [comment]
That is indeed the way I tried. The CDK deploy call in the end is done with the credentials for account B. CDK will throw an error after the first stack that it deploys (an EventBusPolicy stack), that it is not configured with the credentials for the RepoStack to deploy it. My `app.py` code looks something like the following (also, account A = repo account = PROD in the example, and account B = pipeline account = DEV in the example):

```python
dev_env = core.Environment(account=props['dev']['account'], region=props['dev']['region'])
prod_env = core.Environment(account=props['prod']['account'], region=props['prod']['region'])

app = core.App()

repoStack = core.Stack(app, 'Repostack', env=prod_env)

repo = codecommit.Repository.from_repository_arn(
    scope=repoStack,
    id="crossaccount_pipeline_repo",
    repository_arn="arn:aws:codecommit:region:prod_account:repo_name",
)

pipeline_dev = PipeLineStackDev(app, "poc-2-crossacount-pipeline-dev", props['dev'], repo, env=dev_env)

app.synth()
```

`cdk ls` lists the following stacks
```
EventBusPolicy-accountA-region-accountB
Repostack
poc-2-crossacount-pipeline-dev
```

`cdk deploy` deploys the first stack to Dev, and then throws the following error
```
Need to perform AWS calls for account A/PROD, but the current credentials are for B/DEV.
```

**Comment by skinny85** [comment]
Yes, that's a problem with our CLI unfortunately. What you can do is use the `-e` / `--exclusively` switch:

```
$ cdk deploy --profile accA EventBusPolicy-accountA-region-accountB
$ cdk deploy --profile accA Repostack
$ cdk deploy --profile accB -e poc-2-crossacount-pipeline-dev
```

That should work!

BTW, also check out the [CDK Pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) module - it might make your life a little bit easier (depending on what exactly you're deploying in that CodePipeline).

**Comment by mounir-futurefacts** [comment]
Thanks a million Adam! That makes life so much easier, I wonder why it is so hard to find an example of this. The blog post I shared earlier is the only official blogpost I found on it, and it is way more complicated than this.

The CDK Pipelines module is what I am using already btw, can't live without it anymore! :)

PS for anyone reading in the future, the exact final commands were
```bash
cdk deploy --profile accB EventBusPolicyStack    
cdk deploy --profile accA -e  Repostack
cdk deploy --profile accB -e Pipelinestack
```

**Comment by mounir-futurefacts** [comment]
So it turns out this doesn't integrate very well with CDK Pipelines after all...

The reason is that in the selfmutate stage of the pipeline you can not specify this custom setting where you deploy stacks --exclusively. As a consequence, the pipeline runs into permission errors in this stage.

Still in doubt whether I should create a ticket or feature request for this

**Comment by skinny85** [comment]
@mounir-futurefacts yes, you probably should 🙂. A title like "support for cross-account Sources in CDK Pipelines" seems like a good description of your problem 🙂.
