### ISSUE TITLE
[aws-ec2] Instance creation and PlacementGroup options

### ISSUE THREAD

**Issue by nbenaglia** [aws/aws-cdk#11331]
When creating an EC2 instance (new ec2.Instance), it should be possible to specify a placement group where instance belongs.

**Comment by rix0rrr** [comment]
Placement groups are a Launch Template feature, are they not?

**Comment by nbenaglia** [comment]
In AWS::EC2::Instance too there's a PlacementGroup property:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-placementgroupname

And from AWS Console you can launch an EC2, specify the placementGroup, without passing through a launchTemplate.

**Comment by AGSaidi** [comment]
You can do this like the following, but it would be nice to be able to specify it in the constructor.

```
pg = CfnPlacementGroup(self, 'my-placement-group', strategy='cluster')
i = ec2.Instance(self, 'instance-of-mine',
            instance_type=...
i.instance.add_property_override('PlacementGroupName', pg.ref)
```

**Comment by comcalvi** [comment]
fixed by #24775

**Comment by rogerkenny** [comment]
I'm still not seeing a way to specify a placement group when launching an ec2 instance. Am I missing it?

**Comment by pahud** [comment]
@rogerkenny we'll add that support for ec2.Instance from here https://github.com/aws/aws-cdk/issues/30292

**Comment by smeikalr** [comment]
> You can do this like the following, but it would be nice to be able to specify it in the constructor.
> 
> ```
> pg = CfnPlacementGroup(self, 'my-placement-group', strategy='cluster')
> i = ec2.Instance(self, 'instance-of-mine',
>             instance_type=...
> i.instance.add_property_override('PlacementGroupName', pg.ref)
> ```

For Python and Launch Template:

```python
launch_template = ec2.LaunchTemplate(...)
placement_group = ec2.CfnPlacementGroup(self, "my-placement-group", strategy="cluster")
launch_template.node.default_child.add_property_override("LaunchTemplateData.Placement.GroupName", placement_group.ref)
```
