### ISSUE TITLE
gp3 support - Cfn Supports natively but CDK does not

### ISSUE THREAD

**Issue by miztiik** [aws/aws-cdk#12020]
The newly released gp3 volumes are supported by Cloudformation. But `aws_cdk.aws_ec2.EbsDeviceVolumeType` does not support it yet.
Ref: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/EbsDeviceVolumeType.html#aws_cdk.aws_ec2.EbsDeviceVolumeType

**Comment by NetaNir** [comment]
Yup we need to add that type to the enum and modify the conditions to allow it.

**Comment by tpunder** [comment]
Don't forgot about supporting the Throughput and IOPS configuration for GP3 volumes. It probably makes sense also add in IO2 support at the same time too.

**Comment by miztiik** [comment]
> Don't forget about supporting the Throughput and IOPS configuration for GP3 volumes. It probably makes sense also add in IO2 support at the same time too.

Here is the issue for the same - https://github.com/aws/aws-cdk/issues/12052

**Comment by kirintwn** [comment]
This should be close as #12074 was merged.

**Comment by orzikhd** [comment]
The change #12074 doesn't include adding GP3 to `EmrCreateCluster.EbsBlockDeviceVolumeType`

**Comment by mmuller88** [comment]
Just use that downleveling feature like:

```ts
const cfnInstance = instance.node.defaultChild as ec2.CfnInstance;
cfnInstance.blockDeviceMappings = [{
        deviceName: '/dev/sda1',
        ebs: {
          deleteOnTermination: true,
          encrypted: false,
          volumeSize: 2 * 300,
          volumeType: 'gp3',
        },
}];
```

**Comment by ArielPrevu3D** [comment]
`EbsDeviceOptionsBase` needs a throughput option to match [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-throughput)

**Comment by jumic** [comment]
There are three topics mentioned in this issue:
- Volume type GP3 in ec2 --> Resolved by PR #12074.
- Volume type GP3 for EmrCreateCluster.EbsBlockDeviceVolumeType --> This must not be implemented because GP3 is not supported there, see [service documentation](https://docs.aws.amazon.com/emr/latest/APIReference/API_VolumeSpecification.html) and [cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-volumetype). 
- New property [Throughput](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-throughput) in EbsDeviceOptionsBase. --> New feature request, related to GP3. However, GP3 can also used with the default value for property `troughput`. @peterwoodworth To keep it clean: should we add a new feature request (low priority) for this property and close this issue?

**Comment by peterwoodworth** [comment]
@jumic it would be helpful if you create a new feature request for the `throughput` property! If that property can be used for every interface that extends `EbsDeviceOptionsBase` (`EbsDeviceOptions` and `EbsDeviceSnapshotOptions`) then it would make sense to add the `throughput` property here, but let's verify with the area owner first. 

If this is a wanted change, a check should be put in place to ensure that the throughput property is set only if the volume type is gp3.

**Comment by pwrmiller** [comment]
@peterwoodworth - This is still an issue in CDK 2.69.0 for AutoScalingGroup block devices. It seems the generic interface has been fixed, but not the interface included with ASG Block Devices (oddly, it uses its own).
