### ISSUE TITLE
[dynamodb]: when using Dynamodb global table, CDK generates nested stacks with many unexpected roles.

### ISSUE THREAD

**Issue by helenxh** [aws/aws-cdk#12271]
### Reproduction Steps
1. create DatabaseStack.ts by using new dynamodb.Table.

```
import cdk = require('@aws-cdk/core');
import * as dynamodb from '@aws-cdk/aws-dynamodb';

export interface DatabaseStackProps {
    readonly stackName?: string;

    /**
     * Stack tags that will be applied to all the taggable resources and the stack itself.
     *
     * @default {}
     */
    readonly tags?: {
        [key: string]: string;
    };
}

export class DatabaseStack extends Stack {
    constructor(parent: cdk.App, name: string, props: DatabaseStackProps) {
        super(parent, name, {
            env: props.env,
            stackName: props.stackName,
        });
        const globalTable = new dynamodb.Table(this, 'TestTable', {
          partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
          replicationRegions: ['us-east-1', 'eu-west-1']
        });
    }
}
```
2. In app.ts file, generate the DatabaseStack for BOM region
```
    // deploy global table from BOM region
    if ("ap-south-1" == region) {
        stacks.push(new DatabaseStack(app,
            `DatabaseStack-${stageName}`, {
                env: env,
                stageName: stageName
            })
        );
    }
```

### What did you expect to happen?
There should no more IAM role be created.

### What actually happened?

there is a nested CFN stack generated automatically in build/cdk.out folder, include 6 IAM roles.
```

It creates the following 5 IAM roles associated with Lambda functions

1. OnEventHandlerServiceRole15A26729
a. OnEventHandler42BEBAE0
2. IsCompleteHandlerServiceRole5810CC58
a. IsCompleteHandler7073F4DA
3. ProviderframeworkonEventServiceRole9FF04296
a. ProviderframeworkonEvent83C1D0A7
4. ProviderframeworkisCompleteServiceRoleB1087139
a. ProviderframeworkisComplete26D7B0CB
5. ProviderframeworkonTimeoutServiceRole28643D26
a. ProviderframeworkonTimeout0B47CA38

And 1 IAM role associated with step functions

1. ProviderwaiterstatemachineRole0C7159F9
a. Providerwaiterstatemachine5D4A9DF0
```

When deploying DatabaseStack-alpha CFN stack, it deploys DatabaseStack-alpha-awscdkawsdynamodbReplicaProviderNestedStackawscdkawsdynam-1FQEUE5E3XK42 nested stack, with all these roles above.

### Investigation
1. I found in 1.39 aws-dynamodb, the createReplicaTables() function (this was the one that was called when using replicationRegions) refers to a replica provider: https://github.com/aws/aws-cdk/blob/v1.39.0/packages/@aws-cdk/aws-dynamodb/lib/table.ts#L1223 
2. the replicaProvider extends NestedStack: https://github.com/aws/aws-cdk/blob/v1.39.0/packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts
3. I tested Global table feature in my account via AWS Console, it only needs AWSServiceRoleForDynamoDBReplication role. Can refer steps [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables.tutorial.html) This is also confirmed with AWS DynamoDB support team.

### Questions

1. Why CDK needs generate the nest stack with these IAM roles for global table replication feature? 
2. Is there a way to rewrite the CDK construct to avoid generating any IAM roles? 

Thank you.

### Environment

  - **CDK CLI Version  :** v1.39.0
  - **Framework Version:** AWS-CDK v1.39.0
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @helenxh ,

the Roles are related to the fact that global replication support is not available in CloudFormation; and so, the support for it in CDK is implemented using CloudFormation Custom Resources.

The various Lambdas are needed, because the creation of a replica can take a long time, potentially even more than the max Lambda timeout of 15 minutes. Hence, we use a StateMachine with multiple Lambdas (each with its separate Role) to work around that, and have a Custom Resource that can execute for a long time.

Hope that clears this up!

Thanks,
Adam

**Comment by helenxh** [comment]
Hello @skinny85 

Got it. Thanks for the explanation. 

I have some follow up questions. Thanks.
1. Is there a way to rewrite the CDK construct to avoid generating so many IAM roles?
2. I found some of the IAM roles has more permission than needed. For example, OnEventHandlerServiceRoleDefaultPolicy has "Action": "dynamodb:*". Is there any way this construct can restrict these roles to use least privilege?
(Since I noticed that AWSServiceRoleForDynamoDBReplication role should be enough for global table replication. It does not have so much permission neither.)

**Comment by skinny85** [comment]
Hey @helenxh ,

according to the comment in the code: https://github.com/aws/aws-cdk/blob/17f57a5ee49b39aee285bbd1fb3883c319a32fe8/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L1459-L1466

It seems like the `dynamodb:*` is currently required, and there's no way around it.

If you want to experiment with trying to scope those down, feel free to, I'll be glad to change it to something smaller that still works.

Thanks,
Adam

**Comment by smcroskey** [comment]
Looks like global table replication is [now supported](https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-dynamodb-global-tables-now-support-aws-cloudformation/) in CloudFormation for dynamodb.  Can we look at simplifying the resource creation at this point (i.e. avoiding the nested stack)?

**Comment by skinny85** [comment]
Yes! We're discussing it here: https://github.com/aws/aws-cdk/pull/14054#issuecomment-843616601

**Comment by yrathams1** [comment]
Can we override the IAM roles created ? If so, how ?

**Comment by skinny85** [comment]
@yrathams1 for 1., if your customer doesn't want CDK creating Roles for them, I would recommend using the [`CfnGlobalTable` construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.CfnGlobalTable.html). It's a little bit lower-level than the `Table` class, but it allows much more control. The `Table` class with the `replicatedRegions` property uses Custom Resources to support global tables (this was before they had native CloudFormation support), and that's why all of those Roles get created (they are used by the Lambda functions implementing those Custom Resources).

There _is_ a way to change the names of those Roles if the customer doesn't want to use `CfnGlobalTable`, but it's a little tricky. Here's some code that should get the customer going:

```ts
import * as cdk from '@aws-cdk/core';
import * as dynamodb from '@aws-cdk/aws-dynamodb';
import * as iam from '@aws-cdk/aws-iam';

class MyStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        new dynamodb.Table(this, 'Table', {
            // some properties here...
            replicationRegions: ['us-west-1'],
        });
        const nestedStack = this.node.findChild('@aws-cdk/aws-dynamodb.ReplicaProvider');
        renameRoleRecursively(nestedStack);
    }
}

function renameRoleRecursively(construct: cdk.IConstruct): void {
    if (construct instanceof iam.CfnRole) {
        construct.roleName = 'my-role-name';
    } else {
        for (const child of construct.node.children) {
            renameRoleRecursively(child);
        }
    }
}
```

**Comment by skinny85** [comment]
@yrathams1 For 2., if you're changing the names of the bootstrap Roles, you need to tell the CDK about the new names. You do that by changing the properties of the `DefaultStackSynthesizer` your Stacks use. See more information [here](https://github.com/aws/aws-cdk/blob/dad96ffbdb8a4452d5e151d2113da30e195e95cf/packages/%40aws-cdk/core/README.md#stack-synthesizers) and [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.DefaultStackSynthesizer.html).

**Comment by yrathams1** [comment]
@skinny85 Thank you, now that CFT supports global tables is there a plan on updating this class to not use work around? Also is there a plan on providing a way in the future to override these roles like you can do in other CDK classes like lambdas?”

**Comment by skinny85** [comment]
1. We don't have an issue for that in the backlog. Note that, even if we implemented that, it would be behind a feature flag, because there's no way to transition from the Custom Resource-backed implementation to the `CfnGlobalTable`-backed implementation without re-creating the Table (which would be disastrous for a production environment, of course).
2. Again, we don't have an issue for that in the backlog. Feel free to create it.

**Comment by yrathams1** [comment]
Hi @skinny85 My customer is still getting the following error: 
Embedded stack arn:aws:cloudformation:us-east-1:167772905579:stack/on-boarding-bundler-cdk-dynamodb-stack-awscdkawsdyn
amodbReplicaProviderNestedStackawsc-125PLKL7LE01Y/daba9d60-b1db-11ec-a64f-0ae45555f8a1 was not successfully created: The following resource(s) failed to create: [OnEventHandlerServiceRole15A26729, ProviderframeworkonEventServiceRole
9FF04296, ProviderframeworkisCompleteServiceRoleB1087139, ProviderwaiterstatemachineRole0C7159F9, IsCompleteHandlerServiceRole5810CC58, ProviderframeworkonTimeoutServiceRole28643D26]. However, the roles are created with custom names. Are we missing any thing here ?

**Comment by skinny85** [comment]
I don't know - I would need to see the actual error message.

**Comment by skinny85** [comment]
There should be some error message in the CloudFormation output, including in the AWS Console for CloudFormation for that Stack.

**Comment by yrathams1** [comment]
Yes, 

> 

Yes, It is the same error. The error is "The following resource(s) failed to create: [OnEventHandlerServiceRole15A26729, ProviderframeworkonEventServiceRole
9FF04296, ProviderframeworkisCompleteServiceRoleB1087139, ProviderwaiterstatemachineRole0C7159F9, IsCompleteHandlerServiceRole5810CC58, ProviderframeworkonTimeoutServiceRole28643D26]." From what I understand, though it is deploying the roles with the custom role names, the cdk assets are still pointing to the old role names. What do we do to make sure the CDk understands the new custom role names?

**Comment by skinny85** [comment]
No, this is not the error that I'm referring to. Keep looking 🙂. There has to be more information there (most importantly, _why_ did they fail creation).

**Comment by skinny85** [comment]
Also, make sure to implement what I described in this comment: https://github.com/aws/aws-cdk/issues/12271#issuecomment-1085188452.

**Comment by yrathams1** [comment]
Yes, following your recommendation I used some logging and I get ${Token[TOKEN.270]} as the role name if I try to print construct.roleName. Is this expected or has anything to do with the testing/ assignment?
