### ISSUE TITLE
(cloudformation_include): Usage of `Fn::If` breaks diff

### ISSUE THREAD

**Issue by dstoeckel** [aws/aws-cdk#12887]
When including a cloud formation stack that uses `Fn::If` in certain places, cdk diff fails with an exception. I have attached a small example derived from a real world use-case that triggers two of these exceptions. In both cases it affects the creation of an IAM role:

1. The handling of the `ManagedPolicyArns` property assumes that a `string[]` is passed, but in the case of an `Fn::If` a string is passed. (see @aws-cdk/cloudformation-diff/lib/iam/managed-policy.ts)
2. In the case of the `Policies` property an array of policy definitions is assumed. However, if one of these definitions is included conditionally, this assumption breaks. (see @aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts: `readIdentityPolicies`)

### Reproduction Steps

Run `cdk diff` on the following application (Note, that the observed behavior is for a stack that has not yet been deployed either manually or via `cdk deploy`):

CloudFormation template (save as `reproduction.json`):
```json
{
	"Conditions": {
		"HasPolicyArns": {
			"Fn::Equals": [
				"True",
				"True"
			]
		},
		"HasVpc": {
			"Fn::Equals": [
				"True",
				"True"
			]
		}
	},
	"Resources": {
		"TestRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": {
						"Effect": "Allow",
						"Principal": {
							"Service": "codebuild.amazonaws.com"
						},
						"Action": "sts:AssumeRole"
					}
				},
				"ManagedPolicyArns": {
					"Fn::If": [
						"HasPolicyArns",
						[],
						[
							"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
						]
					]
				},
				"Policies": [
					{
						"Fn::If": [
							"HasVpc",
							{
								"PolicyName": "VPC",
								"PolicyDocument": {
									"Version": "2012-10-17",
									"Statement": [
										{
											"Effect": "Allow",
											"Action": "s3:GetObject",
											"Resource": "*"
										}
									]
								}
							},
							{
								"Ref": "AWS::NoValue"
							}
						]
					}
				]
			}
		}
	}
}
```

CDK App:
```python
#!/usr/bin/env python3

from aws_cdk import cloudformation_include as cfn, core

app = core.App()

class Reproduction(core.Stack):
    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cfn.CfnInclude(
            self,
            construct_id,
            template_file="reproduction.json",
        )

dummy = Reproduction(app, "reproduction")

app.synth()
```

### What did you expect to happen?

A diff of the Cfn template is successfully being rendered.

### What actually happened?

Executing `cdk diff` on the following app fails with the exception:

```
arns.map is not a function
TypeError: arns.map is not a function
    at Object.parseManagedPolicies (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/managed-policy.ts:21:15)
    at IamChanges.readManagedPolicies (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:242:4)
    at IamChanges.readPropertyChange (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:154:45)
    at new IamChanges (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:36:12)
    at new TemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:52:23)
    at calculateTemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:110:10)
    at Object.diffTemplate (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:43:19)
    at Object.printStackDiff (/usr/local/lib/node_modules/aws-cdk/lib/diff.ts:24:24)
    at CdkToolkit.diff (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:103:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

When setting `ManagedPolicyArns` to `[]`, `cdk diff` fails with

```
Cannot read property 'Statement' of undefined
TypeError: Cannot read property 'Statement' of undefined
    at /usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:188:8
    at Object.flatMap (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/util.ts:46:17)
    at IamChanges.readIdentityPolicies (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:186:12)
    at IamChanges.readPropertyChange (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:144:40)
    at new IamChanges (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:36:12)
    at new TemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:52:23)
    at calculateTemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:110:10)
    at Object.diffTemplate (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:43:19)
    at Object.printStackDiff (/usr/local/lib/node_modules/aws-cdk/lib/diff.ts:24:24)
    at CdkToolkit.diff (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:103:18)
```

### Environment

  - **CDK CLI Version  :** 1.88
  - **Framework Version:** 1.88
  - **Node.js Version:** v14.15.4
  - **OS               : Fedora 33**
  - **Language (Version):** Python 3.9.1

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for the report @dstoeckel . Interestingly, when I deployed this:

```json
{
    "Conditions": {
        "HasPolicyArns": {
            "Fn::Equals": [
                "True",
                "True"
            ]
        },
        "HasVpc": {
            "Fn::Equals": [
                "True",
                "True"
            ]
        }
    },
    "Resources": {
        "TestRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "codebuild.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                },
                "ManagedPolicyArns": {
                    "Fn::If": [
                        "HasPolicyArns",
                        [],
                        [
                            "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
                        ]
                    ]
                },
                "Policies": [
                    {
                        "Fn::If": [
                            "HasVpc",
                            {
                                "PolicyName": "VPC",
                                "PolicyDocument": {
                                    "Version": "2012-10-17",
                                    "Statement": [
                                        {
                                            "Effect": "Allow",
                                            "Action": "s3:GetObject",
                                            "Resource": "*"
                                        }
                                    ]
                                }
                            },
                            {
                                "Ref": "AWS::NoValue"
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```

And then included it in my CDK code, `cdk diff` succeeded for me, and showed `There were no differences`.

However, changing `ManagedPolicyArns` to `[]` does indeed fail with `arns.map is not a function`.

I have not been able to reproduce the `Cannot read property 'Statement' of undefined` error though.

**Comment by dstoeckel** [comment]
Thanks for confirming @skinny85 ! I can reproduce your observed behavior when I first deploy the stack manually, too. I did not do this for the report above and in this case I can still reproduce the `.Statement` issue.

I'll edit my report to make sure that this was with an yet undeployed stack.

**Comment by skinny85** [comment]
Thanks @dstoeckel  - yep, I confirm I see the same behavior when trying to `diff` against a Stack that doesn't exist!
