### ISSUE TITLE
(aws-mwaa): unable to add tags and airflow_configuration_options via mwaa.CfnEnvironment

### ISSUE THREAD

**Issue by kostiantyn-priv** [aws/aws-cdk#13772]
I am unable to add tags and airflow_configuration_options via mwaa.CfnEnvironment. cdk synth raised error

### Reproduction Steps

```python
class AirflowStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, environment: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        aws_mwaa.CfnEnvironment(
            scope=self,
            id=f'airflow-{environment}-environment',
            name=f'airflow-{environment}-det',
            airflow_configuration_options={'core.default_timezone': 'utc'},
            airflow_version='1.10.12',
            dag_s3_path=f's3://{bucket.bucket_name}/dags',
            environment_class='mw1.small',
            execution_role_arn=role.role_arn,
            kms_key=key.key_id,
            logging_configuration=logging_configuration,
            max_workers=10,
            network_configuration=network_configuration,
            plugins_s3_object_version=None,
            plugins_s3_path=None,
            requirements_s3_object_version=None,
            requirements_s3_path=f's3://{bucket.bucket_name}/requirements.txt',
            source_bucket_arn=bucket.bucket_arn,
            tags={'Environment': environment},
            webserver_access_mode='Private network',
            weekly_maintenance_window_start=None
        )
```

### What did you expect to happen?

Successful creation of the stack

### What actually happened?

The following error occurred while calling cdk synth

```
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    AirflowStack(
  File "venv\lib\site-packages\jsii\_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "stacks\airflow.py", line 112, in __init__
    aws_mwaa.CfnEnvironment(
  File "venv\lib\site-packages\jsii\_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "venv\lib\site-packages\aws_cdk\aws_mwaa\__init__.py", line 95, in __init__
    props = CfnEnvironmentProps(
  File "venv\lib\site-packages\aws_cdk\aws_mwaa\__init__.py", line 774, in __init__
    tags = CfnEnvironment.TagMapProperty(**tags)
TypeError: __init__() got an unexpected keyword argument 'Environment'
```

### Environment

  - **CDK CLI Version  :** 1.94.1
  - **Framework Version:** 
  - **Node.js Version:** v12.16.1
  - **OS               :** Windows Server 2016 Datacenter
  - **Language (Version):** Python (3.8.6)

### Other

If I set the tags to None, the cdk synth succeeds, but in the result AirflowOptions will be empty

--- 

This is :bug: Bug Report

**Comment by webdog** [comment]
@skinny85 Do you think this is related to https://github.com/aws/aws-cdk/issues/12611 -- `airflow_configuration_options` shows the same behavior for me. I noticed that the underlying `AirflowConfigurationOptionsProperty` class as generated in Python has no configuration name mapping in the jsii decorator compared to other Property classes:

```py
@jsii.data_type(
        jsii_type="@aws-cdk/aws-mwaa.CfnEnvironment.AirflowConfigurationOptionsProperty",
        jsii_struct_bases=[],
        name_mapping={},
    )
    class AirflowConfigurationOptionsProperty:
        def __init__(self) -> None:
            '''
            :link: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mwaa-environment-airflowconfigurationoptions.html
            '''
            self._values: typing.Dict[str, typing.Any] = {}

        def __eq__(self, rhs: typing.Any) -> builtins.bool:
            return isinstance(rhs, self.__class__) and rhs._values == self._values

        def __ne__(self, rhs: typing.Any) -> builtins.bool:
            return not (rhs == self)

        def __repr__(self) -> str:
            return "AirflowConfigurationOptionsProperty(%s)" % ", ".join(
                k + "=" + repr(v) for k, v in self._values.items()
            )
```

versus...

```py
    @jsii.data_type(
        jsii_type="@aws-cdk/aws-mwaa.CfnEnvironment.LoggingConfigurationProperty",
        jsii_struct_bases=[],
        name_mapping={
            "dag_processing_logs": "dagProcessingLogs",
            "scheduler_logs": "schedulerLogs",
            "task_logs": "taskLogs",
            "webserver_logs": "webserverLogs",
            "worker_logs": "workerLogs",
        },
    )
    class LoggingConfigurationProperty:
        def __init__(
            self,
            *,
            dag_processing_logs: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnEnvironment.ModuleLoggingConfigurationProperty"]] = None,
            scheduler_logs: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnEnvironment.ModuleLoggingConfigurationProperty"]] = None,
            task_logs: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnEnvironment.ModuleLoggingConfigurationProperty"]] = None,
            webserver_logs: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnEnvironment.ModuleLoggingConfigurationProperty"]] = None,
            worker_logs: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnEnvironment.ModuleLoggingConfigurationProperty"]] = None,
        ) -> None:
            '''
            :param dag_processing_logs: ``CfnEnvironment.LoggingConfigurationProperty.DagProcessingLogs``.
            :param scheduler_logs: ``CfnEnvironment.LoggingConfigurationProperty.SchedulerLogs``.
            :param task_logs: ``CfnEnvironment.LoggingConfigurationProperty.TaskLogs``.
            :param webserver_logs: ``CfnEnvironment.LoggingConfigurationProperty.WebserverLogs``.
            :param worker_logs: ``CfnEnvironment.LoggingConfigurationProperty.WorkerLogs``.

            :link: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mwaa-environment-loggingconfiguration.html
            '''
            self._values: typing.Dict[str, typing.Any] = {}
            if dag_processing_logs is not None:
                self._values["dag_processing_logs"] = dag_processing_logs
            if scheduler_logs is not None:
                self._values["scheduler_logs"] = scheduler_logs
            if task_logs is not None:
                self._values["task_logs"] = task_logs
            if webserver_logs is not None:
                self._values["webserver_logs"] = webserver_logs
            if worker_logs is not None:
                self._values["worker_logs"] = worker_logs
```

Looking at the CFN Resource Spec for [MWAA Configuration Options](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mwaa-environment-airflowconfigurationoptions.html) -- The spec is empty, which is interesting. Two question from my perspective:

* If the spec is empty, should the underlying class only include `self`? From my limited perspective, if the spec is empty but arbitrary values could be expected (Maybe @Ksennios can confirm/not-confirm), then could the property class be built with `(self, **kwargs)`?
* If the underlying spec is empty, could we include a note in the library docs that escape hatches need to be used to add property overrides since none are present?

**Comment by skinny85** [comment]
@webdog I think this is unrelated to #12611 , but it's a similar problem. Most likely, the resource specification for the `AirflowConfigurationOptions` property is wrong - if it's really a key-value pair, then the `AirflowConfigurationOptions` property of the `MWAA::Environment` resource should have type `Json`, not `AirflowConfigurationOptions`, like it does today:

```json
    "AWS::MWAA::Environment": {
      "Attributes": {
        "Arn": {
          "PrimitiveType": "String"
        },
        "WebserverUrl": {
          "PrimitiveType": "String"
        }
      },
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html",
      "Properties": {
        "AirflowConfigurationOptions": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html#cfn-mwaa-environment-airflowconfigurationoptions",
          "Required": false,
          "Type": "AirflowConfigurationOptions",
          "UpdateType": "Mutable"
        },
```

**Comment by skinny85** [comment]
Until we fix this, you can use [property overrides](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set that property, similar to https://github.com/aws/aws-cdk/issues/12611#issuecomment-774255900.

**Comment by skinny85** [comment]
Actually, if somebody could confirm that deploying an MWAA `CfnEnvrionment` with the `airflowConfigurationOptions` property set using escape hatches to a key-value string deploys successfully, I would really appreciate it!

**Comment by skinny85** [comment]
So, this has been fixed in `35.0.0`, released in [CDK version `1.102.0`](https://github.com/aws/aws-cdk/releases/tag/v1.102.0).

Please re-open/comment if you encounter this problem after `1.102.0`.

**Comment by leroyleejh** [comment]
hello @skinny85 
I am still encountering this issue when i try to define `tags` directly when calling `aws_mwaa.CfnEnvironment`

```
airflow = mwaa.CfnEnvironment(
            self,
            id=f"{idmwaa}-env",
            name=f"{idmwaa}-env",
            airflow_configuration_options=mwaa_config,
            airflow_version='2.0.2',
            dag_s3_path='dags',
            environment_class='mw1.small',
            execution_role_arn=mwaa_execution_role.role_arn,
            logging_configuration=logging_config,
            max_workers=5,
            min_workers=2,
            network_configuration=network_configuration,
            source_bucket_arn=s3_bucket_arn,
            webserver_access_mode='PUBLIC_ONLY',
            tags={
                'env': 'dev',
                'description': 'airflow test',
            }
        )
```


error message
```
Traceback (most recent call last):
  File "/Users/Documents/airflow/app.py", line 33, in <module>
    mwaa = MWAAStack(
  File "/usr/local/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/Documents/airflow/libs/mwaa.py", line 165, in __init__
    airflow = mwaa.CfnEnvironment(
  File "/usr/local/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aws_cdk/aws_mwaa/__init__.py", line 99, in __init__
    props = CfnEnvironmentProps(
  File "/usr/local/lib/python3.9/site-packages/aws_cdk/aws_mwaa/__init__.py", line 832, in __init__
    tags = CfnEnvironment.TagMapProperty(**tags)
TypeError: __init__() got an unexpected keyword argument 'env'
```

**Comment by skinny85** [comment]
I think `tags` is not a dictionary, but an instance of the `CfnEnvironment.TagMapProperty` class: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_mwaa/CfnEnvironmentProps.html#aws_cdk.aws_mwaa.CfnEnvironmentProps.tags.

Try passing that, and see if that helps.

**Comment by peterwoodworth** [comment]
The TagMap property is gone from the spec in favor of using the JSON primitive type. Believe this issue is fixed
