### ISSUE TITLE
(aws-iam): Tags are not applied on raw CfnResource(s)

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#13851]
When the `Tags` aspect is applied to a raw `CfnResource` tags are not applied.

This is actually blocking some legit scenarios in CDK, namely any custom resource implemented by the `custom-resource-provider` in the core package, will suffer from this problem:

https://github.com/aws/aws-cdk/blob/7176a5d5208da7d727bbf5112bc12533983380ea/packages/%40aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts#L196-L197

### Reproduction Steps

```ts
const role = new cdk.CfnResource(this, 'Role', {
  type: 'AWS::IAM::Role',
  properties: {
    AssumeRolePolicyDocument: {
      Version: '2012-10-17',
      Statement: [{
        Action: 'sts:AssumeRole',
        Effect: 'Allow',
        Principal: {
          Service: 'lambda.amazonaws.com'
        }
      }],
    },
  },
});

cdk.Tags.of(role).add('key', 'value');
```

Generates the following template:

```json
"Role": {
  "Type": "AWS::IAM::Role",
  "Properties": {
    "AssumeRolePolicyDocument": {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": "lambda.amazonaws.com"
          }
        }
      ]
    }
  },
},
```

### What did you expect to happen?

Expected tags to be applied to all roles, regardless of what class is used to represent it.

```json
"Role1ABCC5F0": {
  "Type": "AWS::IAM::Role",
  "Properties": {
    "AssumeRolePolicyDocument": {
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": "lambda.amazonaws.com"
          }
        }
      ],
      "Version": "2012-10-17"
    },
    "Tags": [
      {
        "Key": "key",
        "Value": "value"
      }
    ]
  },
  "Metadata": {
    "aws:cdk:path": "EKSIssue13783/Role/Resource"
  }
},
```

### What actually happened?

The tags are not applied.

### Environment

  - **CDK CLI Version  : ALL**
  - **Framework Version: ALL**
  - **Node.js Version: ALL** 
  - **OS               : ALL**
  - **Language (Version): ALL** 

### Other

Root cause is:

https://github.com/aws/aws-cdk/blob/7176a5d5208da7d727bbf5112bc12533983380ea/packages/%40aws-cdk/core/lib/tag-manager.ts#L238-L240

Might be a bit tricky to identify taggable this. But if we could lower this entire inspection to the L0 layer, that would be highly beneficial. 

This might be more appropriate as a feature request.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
There's more problems with the custom resources, or the use of L2 bypasses in general.\

The NodeJS 14 doesn't support inline code debacle was also caused by bypassing the L2 (that does that validation) and yolo'ing in a `CfnResource` into the template.

**Comment by AjkayAlan** [comment]
Another example: when using the `autoDeleteObjects` prop on an S3 Bucket, it will create both an `AWS::Lambda::Function` and an `AWS::IAM::Role` via the `custom-resource-provider` which are untagged.

**Comment by otaviomacedo** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/14754.

**Comment by marcm-ml** [comment]
@otaviomacedo Hey, sorry for the ping. Curiously, I still encounter this behaviour with the S3Bucket autoDeletion CfnResource. Do you have any idea why this might happen?

CDK CLI version: 2.1029.0
CDK version: 2.214.0

I have these feature flags enabled (auto-generated from the CLI)
```json
{
  "app": "ts-node --prefer-ts-exts main.ts",
  "context": {
    "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
    "@aws-cdk/aws-apigateway:authorizerChangeDeploymentLogicalId": true,
    "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
    "@aws-cdk/aws-apigateway:requestValidatorUniqueId": true,
    "@aws-cdk/aws-appsync:appSyncGraphQLAPIScopeLambdaPermission": true,
    "@aws-cdk/aws-appsync:useArnForSourceApiAssociationIdentifier": true,
    "@aws-cdk/aws-autoscaling:generateLaunchTemplateInsteadOfLaunchConfig": true,
    "@aws-cdk/aws-cloudwatch-actions:changeLambdaPermissionLogicalIdForLambdaAction": true,
    "@aws-cdk/aws-codedeploy:removeAlarmsFromDeploymentGroup": true,
    "@aws-cdk/aws-codepipeline-actions:useNewDefaultBranchForCodeCommitSource": true,
    "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
    "@aws-cdk/aws-codepipeline:crossAccountKeysDefaultValueToFalse": true,
    "@aws-cdk/aws-codepipeline:defaultPipelineTypeToV2": true,
    "@aws-cdk/aws-dynamodb:resourcePolicyPerReplica": true,
    "@aws-cdk/aws-dynamodb:retainTableReplica": true,
    "@aws-cdk/aws-ec2:bastionHostUseAmazonLinux2023ByDefault": true,
    "@aws-cdk/aws-ec2:ebsDefaultGp3Volume": true,
    "@aws-cdk/aws-ec2:ec2SumTImeoutEnabled": true,
    "@aws-cdk/aws-ec2:launchTemplateDefaultUserData": true,
    "@aws-cdk/aws-ec2:requirePrivateSubnetsForEgressOnlyInternetGateway": true,
    "@aws-cdk/aws-ec2:restrictDefaultSecurityGroup": true,
    "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
    "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
    "@aws-cdk/aws-ecs:disableEcsImdsBlocking": true,
    "@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker": true,
    "@aws-cdk/aws-ecs:enableImdsBlockingDeprecatedFeature": false,
    "@aws-cdk/aws-ecs:reduceEc2FargateCloudWatchPermissions": true,
    "@aws-cdk/aws-ecs:removeDefaultDeploymentAlarm": true,
    "@aws-cdk/aws-efs:denyAnonymousAccess": true,
    "@aws-cdk/aws-efs:mountTargetOrderInsensitiveLogicalId": true,
    "@aws-cdk/aws-eks:nodegroupNameAttribute": true,
    "@aws-cdk/aws-elasticloadbalancingV2:albDualstackWithoutPublicIpv4SecurityGroupRulesDefault": true,
    "@aws-cdk/aws-events:eventsTargetQueueSameAccount": true,
    "@aws-cdk/aws-events:requireEventBusPolicySid": true,
    "@aws-cdk/aws-iam:importedRoleStackSafeDefaultPolicyName": true,
    "@aws-cdk/aws-iam:minimizePolicies": true,
    "@aws-cdk/aws-iam:oidcRejectUnauthorizedConnections": true,
    "@aws-cdk/aws-kms:aliasNameRef": true,
    "@aws-cdk/aws-kms:applyImportedAliasPermissionsToPrincipal": true,
    "@aws-cdk/aws-kms:reduceCrossAccountRegionPolicyScope": true,
    "@aws-cdk/aws-lambda-nodejs:sdkV3ExcludeSmithyPackages": true,
    "@aws-cdk/aws-lambda-nodejs:useLatestRuntimeVersion": true,
    "@aws-cdk/aws-lambda:createNewPoliciesWithAddToRolePolicy": false,
    "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
    "@aws-cdk/aws-lambda:useCdkManagedLogGroup": true,
    "@aws-cdk/aws-opensearchservice:enableOpensearchMultiAzWithStandby": true,
    "@aws-cdk/aws-rds:auroraClusterChangeScopeOfInstanceParameterGroupWithEachParameters": true,
    "@aws-cdk/aws-rds:databaseProxyUniqueResourceName": true,
    "@aws-cdk/aws-rds:preventRenderingDeprecatedCredentials": true,
    "@aws-cdk/aws-rds:setCorrectValueForDatabaseInstanceReadReplicaInstanceResourceId": true,
    "@aws-cdk/aws-redshift:columnId": true,
    "@aws-cdk/aws-route53-patters:useCertificate": true,
    "@aws-cdk/aws-route53-targets:userPoolDomainNameMethodWithoutCustomResource": true,
    "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
    "@aws-cdk/aws-s3:keepNotificationInImportedBucket": false,
    "@aws-cdk/aws-s3:publicAccessBlockedByDefault": true,
    "@aws-cdk/aws-s3:serverAccessLogsUseBucketPolicy": true,
    "@aws-cdk/aws-s3:setUniqueReplicationRoleName": true,
    "@aws-cdk/aws-secretsmanager:useAttachedSecretResourcePolicyForSecretTargetAttachments": true,
    "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
    "@aws-cdk/aws-stepfunctions-tasks:enableEmrServicePolicyV2": true,
    "@aws-cdk/aws-stepfunctions-tasks:fixRunEcsTaskPolicy": true,
    "@aws-cdk/aws-stepfunctions:useDistributedMapResultWriterV2": true,
    "@aws-cdk/core:aspectPrioritiesMutating": true,
    "@aws-cdk/core:cfnIncludeRejectComplexResourceUpdateCreatePolicyIntrinsics": true,
    "@aws-cdk/core:checkSecretUsage": true,
    "@aws-cdk/core:enableAdditionalMetadataCollection": true,
    "@aws-cdk/core:enablePartitionLiterals": true,
    "@aws-cdk/core:explicitStackTags": true,
    "@aws-cdk/core:includePrefixInUniqueNameGeneration": true,
    "@aws-cdk/core:target-partitions": ["aws", "aws-cn"],
    "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
    "@aws-cdk/custom-resources:logApiResponseDataPropertyTrueDefault": false,
    "@aws-cdk/customresources:installLatestAwsSdkDefault": false,
    "@aws-cdk/s3-notifications:addS3TrustKeyPolicyForSnsSubscriptions": true,
    "acknowledged-issue-numbers": [34892],
    "cli-telemetry": false
  },
  "watch": {
    "exclude": [
      "README.md",
      "cdk*.json",
      "**/*.d.ts",
      "**/*.js",
      "tsconfig.json",
      "package*.json",
      "yarn.lock",
      "node_modules",
      "test"
    ],
    "include": ["**"]
  }
}

```
