### ISSUE TITLE
(eks): helm install - kube config is insecure

### ISSUE THREAD

**Issue by mrsiejas** [aws/aws-cdk#14416]
When deploying stack with helm chart, getting the following error related to insecure kube config created by Lambda:

```
9:45:21 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | FluentBit/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Error: b'WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /tmp/kubeconfig\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /tmp/kubeconfig\nError: UPGRADE FAILED: an
other operation (install/upgrade/rollback) is in progress\n'
```

Code snippet:
```
        chart = self.add_chart(
            id='FluentBit',
            chart='fluent-bit',
            namespace='monitoring',
            repository='https://charts.helm.sh/stable',
            release='fluent-bit',
            values={
                'existingConfigMap': 'fluent-bit-config',
                'image': {
                    'fluent_bit': {
                        'tag': '1.5.6'
                    }
                },
                'parsers': {
                    'enabled': True
                },
                'serviceAccount': {
                    'create': False,
                    'name': service_account.service_account_name
                },
                'tolerations': [
                    {
                        'operator': 'Exists'
                    }
                ],
                'priorityClassName': 'system-node-critical'
            },
            version='2.10.0',
            wait=True,
            timeout=core.Duration.minutes(15)
        )
```

### Reproduction Steps
1. running on CDK v1.93, intend to update existing fluentbit chart deployed on EKS
2. run cdk deploy <stack_name_with_helm_chart>

### What did you expect to happen?

Expect Helm chart to install and update helm chart successfully. Alternatively be able to suppress or ignore this warning (which is sent to stderr).

### What actually happened?

cdk deploy fails and I'm not able to deploy helm on EKS.

### Environment

  - **CDK CLI Version  : 1.93**
  - **Framework Version: **
  - **Node.js Version: v10.24.0** 
  - **OS               : OSX (via Docker container, image: python:3.8.5-slim-buster)**
  - **Language (Version): Python (3.8.5)**

### Other

Can be related to this change: https://github.com/helm/helm/pull/8779 where warning messages are being sent to stderr rather than stdout. 

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@mrsiejas I don't think those warnings are whats causing the failure. I deployed the dashboard using helm:

```ts
cluster.addHelmChart('dashboard', {
  chart: 'kubernetes-dashboard',
  repository: 'https://kubernetes.github.io/dashboard/',
});
```

And it successfully despite those warnings:

```console
[INFO]	2021-05-05T10:25:13.417Z	a5811ffd-8493-4ea7-b3ed-eaabebc456e6	b'WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /tmp/kubeconfig\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /tmp/kubeconfig\nRelease "eksclusterchartdashboarde22e314d" does not exist. Installing it now.\nNAME: eksclusterchartdashboarde22e314d\nLAST DEPLOYED: Wed May  5 10:25:12 2021\nNAMESPACE: default\nSTATUS: deployed\nREVISION: 1\nTEST SUITE: None\nNOTES:\n*********************************************************************************\n*** PLEASE BE PATIENT: kubernetes-dashboard may take a few minutes to install ***\n*********************************************************************************\n\nGet the Kubernetes Dashboard URL by running:\n  export POD_NAME=$(kubectl get pods -n default -l "app.kubernetes.io/name=kubernetes-dashboard,app.kubernetes.io/instance=eksclusterchartdashboarde22e314d" -o jsonpath="{.items[0].metadata.name}")\n  echo https://127.0.0.1:8443/\n  kubectl -n default port-forward $POD_NAME 8443:8443\n'
```

Note that the log you posted also contains:

```console
UPGRADE FAILED: an
other operation (install/upgrade/rollback) is in progress\n'
```

Which I'm fairly certain is the real culprit. Looks like the previous installation must not have finished yet? You'll have to debug that a bit further.

**Comment by mrsiejas** [comment]
I've destroyed the stack. Rerun cdk deploy and still getting the error - no 
```6:27:53 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | FluentBit/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Error: b'WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /tmp/kubeconfig\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /tmp/kubeconfig\nError: UPGRADE FAILED: an
other operation (install/upgrade/rollback) is in progress\n'
```

Maybe this is a race condition somewhere in the stack? The odd thing is that the same stack was deploying fine until recently, the changes made were bumping CDK version from 1.74 -> 1.93 and upgrading EKS to 1.19. 
```UPGRADE FAILED: an
other operation (install/upgrade/rollback) is in progress\n'
```

**Comment by mrsiejas** [comment]
Afaik helm version bundled into Lambda that deploy the charts so maybe we are running different helm versions?
helm/helm#8779 this change looks like a culprit to me. Changing the stdout to stderr could cause CDK to fail as get different exit code from helm.

**Comment by mrsiejas** [comment]
I think you were right @iliapolo. The warning was not causing the chart to fail, it was a problem with Fluentbit immutable selector and the fact I was trying to update it via cdk deploy. Surprisingly cdk destroy didn't remove the old Helm chart.

Still, I do believe the kube config permissions warning should be addressed and fixed for clarity. Having multiple unrelated errors in the output makes it more difficult to troubleshoot the actual issue. Thanks for looking into it.

**Comment by iliapolo** [comment]
Opened https://github.com/aws/aws-cdk/issues/14560 to follow up on the warnings. Resolving this one.
