### ISSUE TITLE
#14611 (aws-iam): edit the trust relationship in ECS-task-instance-role via CDK

### ISSUE THREAD

**Issue by TiffanyHsuuuu** [aws/aws-cdk#14617]
Hello, 
so following the ticket 14611, I wrote below but I still got an error at principals.
Could you please help?

**Comment by TiffanyHsuuuu** [comment]
Hey @rix0rrr 
So I checked the document of principals again and have following code. So this time I don't have any errors. The weird things are after I transform the stack to CF and deploy to my AWS account. I still don't see any changes at trust relationship in console(plz see below image). Could you please let me know what else I should fix?

>    
// add STS trust policy to ecsTaskRole
    const stsPolicy = new SecurePolicyStatement({
        effect: Effect.ALLOW,
        actions: ['sts:AssumeRole'],
        resources: ["*"],
    });
    ecsTaskInstanceRole.addToPolicy(stsPolicy);

    //the application-specific roles need to specify trust policy to allow devAccount to assume them
    ecsTaskInstanceRole.assumeRolePolicy?.addStatements(
        new SecurePolicyStatement({
            effect: Effect.ALLOW,
            actions: ['sts:AssumeRole'],
            principals: [new SecureServicePrincipal("arn:aws:iam::user:root")]
        })
    );
![image](https://user-images.githubusercontent.com/50206789/117716119-7d1cef80-b1d9-11eb-93f7-6ef34b821eba.png)

**Comment by peterwoodworth** [comment]
Hey @TiffanyHsuuuu 

The docs page [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-iam-readme.html#iam-principals) has a ton of good info related to using principals.

Here's an example I deployed that should help you out:

```ts
const myStatement = new iam.PolicyStatement({
  effect: iam.Effect.ALLOW,
  actions: ['sts:AssumeRole']
})

myStatement.addArnPrincipal('arn:aws:iam::123456789012:root')

myRole.assumeRolePolicy?.addStatements(myStatement)
```

**Comment by TiffanyHsuuuu** [comment]
Hey @peterwoodworth 
Thank you for the reply :)
I wrote exactly what you typed here, but I still get an error that `Argument of type 'string' is not assignable to parameter of type 'never'`....(Please see photo) I'm not fully following why it doesn't work in my case. Could you please advise it? 
![image](https://user-images.githubusercontent.com/50206789/117760695-63ee6000-b226-11eb-8df1-268f82d56320.png)

**Comment by peterwoodworth** [comment]
Where exactly are you getting `SecurePolicyStatement` from?

Are all of your CDK packages in `packages.json` the same version?

**Comment by peterwoodworth** [comment]
@TiffanyHsuuuu where are you getting `SecurePolicyStatement` from? The class found in IAM is just `iam.PolicyStatement`

**Comment by TiffanyHsuuuu** [comment]
> Where exactly are you getting `SecurePolicyStatement` from?
> 
> Are all of your CDK packages in `packages.json` the same version?

Hey :) just to reply your question, it's from an internal library. I guess that's where the problem comes from. I guess I need to try some other ways in this case. Do you possibly know if there're some other ways to attach my AWS root account to the task-role for trust relationship by using CDK?
