### ISSUE TITLE
(custom-resources): Permissions boundaries not applied to all roles

### ISSUE THREAD

**Issue by cyuste** [aws/aws-cdk#15572]
### Reproduction Steps

Code example [here](https://github.com/cyuste/testBoundaries)
Before synthesising an account/region must be configured in the [stack options](https://github.com/cyuste/testBoundaries/blob/e6eccfde25aab1fd0202f1d9f1666b21bfdcc36b/bin/test-boundaries.ts#L8)
and after configure a vpc name that exist in the account/region [here](https://github.com/cyuste/testBoundaries/blob/e6eccfde25aab1fd0202f1d9f1666b21bfdcc36b/lib/test-boundaries-stack.ts#L12)

### What did you expect to happen?
In the stack definition we have declared at the end
```
 const permissionsBoundaryArn = `arn:aws:iam::${cdk.Aws.ACCOUNT_ID}:policy/CDKAppScopePermissions`;
 iam.PermissionsBoundary.of(this).apply(iam.ManagedPolicy.fromManagedPolicyArn(this, 'xx', permissionsBoundaryArn));
```
With this we would expect to have this permissionsBoundary applied to all the roles created in the stack

### What actually happened?
Two roles are created, one of them does not have permissionsBoundaries correctly applied. If we modify the stack in [this line](https://github.com/cyuste/testBoundaries/blob/e6eccfde25aab1fd0202f1d9f1666b21bfdcc36b/lib/test-boundaries-stack.ts#L43)
from:
```
parameters: { NetworkInterfaceIds: interfaceIds },
```
to:
```
parameters: { NetworkInterfaceIds:['a','b'] },
```
the stack contains only one role with the permissionsBoundaries correctly applied

### Environment

  - **CDK CLI Version  :** 1.113.0

  - **Node.js Version:** v14.17.0
  - **OS               :**  OSX
  - **Language (Version):**  TypeScript (3.9.7) 

### Other
I also tried to use aspects and configure Role and CfnRole as targets but obtained the same result. I created this repo as the minimal code required to show the issue, but obviously this is not my actual cdk project.

Some issues I think might be related:
#3242
#13310

--- 

This is :bug: Bug Report

**Comment by Pandafriendd** [comment]
I have done some research and testings, and based on the CDK module source code, the role that did not get applied with the permission boundary is created by CDK along with a Lambda function and custom resource, to manage JSON stringifying and encoding . That's why when you defining parameters like `parameters: { NetworkInterfaceIds:['a','b'] }` then that role and Lambda function / custom resource were not created, but `parameters: { NetworkInterfaceIds: interfaceIds }` does. That's because latter needs JSON stringify/encode which processed via the CDK managed Lambda.

See the `AwsCustomResource` code [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L410-L412), and the CDK managed Lambda [here](https://github.com/aws/aws-cdk/blob/7966f8d48c/packages/%40aws-cdk/core/lib/private/cfn-utils-provider/index.ts) from `cfn-utils-provider`.

Now the question is how we can override the CDK managed Lambda and its role, as I have tried override using child of stack/construct and `Aspects`, none of works. It seems that it is not belong to any construct or not a child of any construct in the stack.

Could CDK team/community shed some lights regarding above findings?

**Comment by polothy** [comment]
This might have been fixed with https://github.com/aws/aws-cdk/pull/16154

**Comment by cyuste** [comment]
Retested with cdk v1.123.0 (cli and packages version). Still reproduced

**Comment by RobertAlblas** [comment]
I can still reproduce this problem, any idea how to work around it?
