### ISSUE TITLE
‼️ NOTICE: jsii libraries using v2 (`aws-cdk-lib`) require specific import format

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#17860]
### What is the problem?

Please add your +1 👍 to let us know you have encountered this

----

## Overview

When writing plain TypeScript applications using CDK v2 (`aws-cdk-lib`), you can use one of two different import styles:

```ts
// Both of these are allowed for TypeScript apps/libs
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import { aws_ec2 as ec2 } from 'aws-cdk-lib';
```

When writing jsii libraries against CDK v2 (`aws-cdk-lib`), you can currently only use one of those import formats. It must be:

```ts
// Only this one is currently supported by jsii
import { aws_ec2 as ec2 } from 'aws-cdk-lib';
```

If you use the other one, you will see an error like:

```
index.ts:4:12 - error JSII3002: Type "aws-cdk-lib.IVpc" cannot be used as a property type because it is not exported from aws-cdk-lib
```

## Resolution

The issue has been resolved as of jsii `1.48.0`. Make sure you are using that version or higher when writing construct libraries for v2, and you want to use the particular import statement style that doesn't work otherwise.

**Comment by RichiCoder1** [comment]
I'm getting this error no matter which style I use, so looking forward to a firmer resolution.

**Comment by ldecaro** [comment]
The above proposed solution doesn't work on the use case below. Any ideas?

```
import {Annotations, CfnOutput, IAspect, Stack} from 'aws-cdk-lib';
import {aws_apigateway as api} from 'aws-cdk-lib';
import {aws_iam as iam} from 'aws-cdk-lib';
import {IConstruct} from 'constructs';
export class ApiGatewayHelpers {
public static endpointConfiguration(stack: Stack, group?: string): api.EndpointConfiguration {
const vpcInfo = VpcHelpers.lookupVpcInfo(Stack.of(stack), group)
return {types: [api.EndpointType.PRIVATE], vpcEndpoints: [vpcInfo.apigwEndpointId]}
}
```

error JSII3002: Type "aws-cdk-lib.EndpointConfiguration" cannot be used as a return type because it is not exported from aws-cdk-lib

9 public static endpointConfiguration(stack: Stack, group?: string): api.EndpointConfiguration {
~~~~~~~~~~~~~~~~~~~~~
node_modules/aws-cdk-lib/aws-apigateway/lib/restapi.d.ts:626:1
626 export interface EndpointConfiguration {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
627 /**
~~~~~~~
...
640 readonly vpcEndpoints?: IVpcEndpoint[];
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
641 }
~
The referenced type is declared here
lib/api-gateway-helpers.ts:44:17 - error JSII3002: Type "aws-cdk-lib.PolicyDocument" cannot be used as a return type because it is not exported from aws-cdk-lib

**Comment by biffgaut** [comment]
We pinned jsii at 1.47 in our package.json file for the time being, that kept us moving until there's a better solution.

**Comment by RichiCoder1** [comment]
Have either of ya'll had a chance to see if https://github.com/aws/jsii/releases/tag/v1.49.0 resolves this issue or is it still present?

**Comment by RichiCoder1** [comment]
Update: This _appears_ to have been fixed in v1.49 for me

**Comment by rix0rrr** [comment]
@ldecaro are you still seeing this in 1.48 or later?

**Comment by biffgaut** [comment]
We still see it in 1.49 when building for CDK V2

@aws-solutions-constructs/aws-kinesisstreams-gluejob: lib/index.ts:75:12 - error JSII3002: Type "aws-cdk-lib.CfnTable.ColumnProperty" cannot be used as a list element type because it is not exported from aws-cdk-lib

**Comment by rix0rrr** [comment]
@biffgaut I tried reproducing that but seems to work for me.

When I did the following:

* Ran `npx -p aws-cdk-migration rewrite-imports-v2 **/*.ts` on `@aws-solutions-constructs/core` and `@aws-solutions-constructs/aws-kinesisstreams-gluejob`
* Updated `package.json` to depend on `aws-cdk-lib@2.1.0`
* Updated `package.json` to depend on `jsii@1.49.0`.
* Got rid of the `test/` directories because they needed some source changes I was not prepared to make

It seems to work for me:

```
huijbers ~/D/a/s/p/@/core(migrate-to-v2)> npx jsii
lib/lambda-event-source-mapping-defaults.ts:24:14 - warning JSII5019: The property name "eventSourceProps" conflicts with the declaring interface "EventSourceProps". This will result in renaming the interface to "_EventSourceProps" in C#. Consider renaming "eventSourceProps".

24     readonly eventSourceProps?: StreamEventSourceProps,
                ~~~~~~~~~~~~~~~~

  lib/lambda-event-source-mapping-defaults.ts:23:18
    23 export interface EventSourceProps {
                        ~~~~~~~~~~~~~~~~
    The declaring interface is introduced here
huijbers ~/D/a/s/p/@/core(migrate-to-v2)> cd ../aws-kinesisstreams-gluejob/
huijbers ~/D/a/s/p/@/aws-kinesisstreams-gluejob(migrate-to-v2)> npx jsii
huijbers ~/D/a/s/p/@/aws-kinesisstreams-gluejob(migrate-to-v2)> npx jsii --version
1.49.0 (build e322d87), typescript 3.9.10
```

Code here:  https://github.com/rix0rrr/aws-solutions-constructs/pull/1

**Comment by rix0rrr** [comment]
If anyone still has issues with this, can you please make me a repro?

**Comment by ldecaro** [comment]
@rix0rrr I’m not seeing the error described on 1.48.

Thanks.

**Comment by biffgaut** [comment]
It cleared up for us when we moved up to building on CDK 2.2.0 (we were several RCs back, I imagine it would have cleared up with 2.1.0 as well)

**Comment by am29d** [comment]
I had the same issue with cdk version `2.1.0` jsii `1.47.0`: 

``` 
error JSII9002: Unable to resolve type "aws-cdk-lib.LayerVersion". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").```

After an update to CDK `2.2.0` the issue was resolved, jsii is still at `1.47.0`.
