### ISSUE TITLE
(aws-cloudfront): changing Function name breaks deployment

### ISSUE THREAD

**Issue by flavioleggio** [aws/aws-cdk#19014]
### What is the problem?

When a CloudFront Function is created with a specific value in the `functionName` attribute, changing it afterwards breaks the deployment with this error: `Resource handler returned message: "Resource of type 'AWS::CloudFront::Function' with identifier 'MyFunction' was not found."`

### Reproduction Steps

Create and deploy a stack with a function and specify a `functionName`

```ts
const rewriteFunction = new Function(this, "RewriteFunction", {
  code: FunctionCode.fromInline(`function handler(event) {  return request; }`),
  functionName: "MyFunction",
});
```

Change the function name and deploy again

```ts
const rewriteFunction = new Function(this, "RewriteFunction", {
  code: FunctionCode.fromInline(`function handler(event) {  return request; }`),
  functionName: "MyFunctionWithANewName",
});
```

### What did you expect to happen?

This change should require a resource replacement (as one cannot really change a function name after it is created), creating a new Function with that name and then removing the old Function.

### What actually happened?

The error `Resource handler returned message: "Resource of type 'AWS::CloudFront::Function' with identifier 'MyFunctionWithANewName' was not found."` is thrown during the second deploy.

### CDK CLI Version

2.10.0

### Framework Version

2.10.0

### Node.js Version

v16.13.0

### OS

Linux

### Language

Typescript

### Language Version

4.1.3

**Comment by NGL321** [comment]
Hey @flavioleggio,

Thank you for reporting this! In this case this was born of a misunderstanding, but we appreciate any and all reports that could help improve the CDK in the future.

To clear up the misunderstanding. This is a problem with how Cloudformation handles resource [Logical IDs](https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html#identifiers_logical_ids). Because LogicalIDs are the root level unique identifiers within Cloudformation, when one is changed and the new template deployed, cloudformation views it as a deletion of the resource with the original logicalID and the creation of a new resource with the new logicalID. This can break update deployment.
The best way to resolve this conflict is to delete the original stack and redeploy the update as a new stack, or to unblock with [`renameLogicalId()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Stack.html#renamewbrlogicalwbridoldid-newid).

I hope this helps resolve your issue!

**Comment by flavioleggio** [comment]
Hi @NGL321,

Thank you for your support on this. I still don’t get why this is an issue with LogicalIDs though. In my example scenario the Function’s construct ID `RewriteFunction` is the same in the second deploy: the only change is the `functionName` attribute.

**Comment by peterwoodworth** [comment]
I've found the same behavior as you. This is an issue with the way CloudFormation handles the functionName attribute. [Typically](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-functionname), changing the name of a CfnResource will cause a resource replacement. However in this case, it causes [no interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html#cfn-cloudfront-function-name)

Reported internally to Cfn team. Tracking: V528982041

**Comment by peterwoodworth** [comment]
Closing - Ticket has been addressed internally. Please let me know if you continue to run into this issue

**Comment by fredericbarthelet** [comment]
@peterwoodworth thanks for reporting this to the internal CFN team. 
However, I've experienced  the issue no later than yesterday and it still seems that there are no fix deployed at the moment. See issue https://github.com/getlift/lift/issues/247#issuecomment-1208195082 for additional information.

Can you help on the matter ?

**Comment by peterwoodworth** [comment]
You're right, I can still reproduce this. I'll bring this back up with the service team

**Comment by redaLaanait** [comment]
I'm experiencing the same issue. Any feedback?

Changing the Logical ID simultaneously with the physical one worked for me.

**Comment by peterwoodworth** [comment]
Ok it should be fixed now. I was able to test this and it works. Please feel free anyone to ping me again if you run into any errors

**Comment by MrBahur** [comment]
I had the same issue now
