### ISSUE TITLE
(opensearch): Some configuration options are not available for use 

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-cdk#28133]
### Describe the feature

This is duplicated from https://github.com/aws/aws-cdk/issues/16575 which should not have been closed. This is blocked on [Cloudformation support](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/832), but should be added once this support is available.

It is not possible to disable Auto-Tune when creating a new OpenSearch domain.

### Use Case

To allow use of domains without Auto-Tune. To allow for use of cheap instances that don't support Auto-Tune without custom resources or other hacks.

### Proposed Solution

Once Cloudformation supports Auto-Tune, expose the parameter in the CDK construct.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.110.1

### Environment details (OS name and version, etc.)

Ubuntu (Windows Subsystem for Linux)

**Comment by pahud** [comment]
OK. As soon as https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/832 is resolved, we should be allowed to have CDK support for it.

**Comment by IllarionovDimitri** [comment]
are there any updates to this issue? cdk seems still not to support auto-tune setting. auto-tune must be enabled for multi-az-with-stand-by. but how to do it?

**Comment by pahud** [comment]
> are there any updates to this issue? cdk seems still not to support auto-tune setting. auto-tune must be enabled for multi-az-with-stand-by. but how to do it?

still pending on https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/832
