### ISSUE TITLE
(aws-synthetics): new Synthetics Runtimes are not supported 

### ISSUE THREAD

**Issue by stone8** [aws/aws-cdk#29141]
### Describe the bug

The Synthetics CDK code (https://github.com/aws/aws-cdk/blob/v2.127.0/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts) doesn't support the new versions released recently (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html): the missing versions include
syn-nodejs-puppeteer-6.2
syn-nodejs-puppeteer-5.2
syn-python-selenium-2.1

### Expected Behavior

It is expected the https://github.com/aws/aws-cdk/blob/v2.127.0/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts should support the newly release versions:
syn-nodejs-puppeteer-6.2
syn-nodejs-puppeteer-5.2
syn-python-selenium-2.1

### Current Behavior

Currently, https://github.com/aws/aws-cdk/blob/v2.127.0/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts doesn't support the newly release versions:
syn-nodejs-puppeteer-6.2
syn-nodejs-puppeteer-5.2
syn-python-selenium-2.1

### Reproduction Steps

https://github.com/aws/aws-cdk/blob/v2.127.0/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts shows the following newly release versions are not supported:
https://github.com/aws/aws-cdk/blob/v2.127.0/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts

### Possible Solution

Add the newly released Synthetics Runtime versions to the https://github.com/aws/aws-cdk/blob/v2.127.0/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts

### Additional Information/Context

This is urgent, as the following older versions will be deprecated soon. 
syn-nodejs-puppeteer-6.1
syn-nodejs-puppeteer-5.1
syn-python-selenium-2.0

### CDK CLI Version

v2.128.0

### Node.js Version

nodejs 16.x and nodejs 18.x

### OS

AWS Lambda

### Language

TypeScript

**Comment by kellertk** [comment]
The CloudWatch synthetics runtime versions that are present are scheduled to be deprecated by 8 Mar 2024. That means this module will need updating before that date.

**Comment by kellertk** [comment]
@wilhen01 got to this one before I did. This issue was fixed by #29132

**Comment by AlessandroVol23** [comment]
I've installed the latest CDK version (`2.133.0`) and it seems the newer versions are still not available right?
![image](https://github.com/aws/aws-cdk/assets/19362086/5e1714a0-9c44-4fa4-93ae-46fb56e370a5)

**Comment by wilhen01** [comment]
@AlessandroVol23 that screenshot contains the latest versions of the NodeJS runtime (6.2, 5.2). I can't actually see it in the screenshot but Python 2.1 should be in there too.
