### ISSUE TITLE
aws-cdk-lib/aws-chatbot: Tag elements cannot contain whitespaces

### ISSUE THREAD

**Issue by nguyentoanit** [aws/aws-cdk#30381]
### Describe the bug

Recently, CDK failed to update stacks.
Looks like, an internal service (**WheatleyOrchestration**) didn't accept Tag elements contain whitespaces.

### Expected Behavior

The internal service accepts Tag elements contain whitespaces.

### Current Behavior

CDK couldn't update `SlackChannelConfiguration` because an internal service required Tag elements without whitespaces.
```
Resource handler returned message: "An error occurred from the supplied tags: Tag elements cannot contain whitespaces (Service: WheatleyOrchestration; Status Code: 400; Error Code: InvalidRequestException; Request ID: b20ea829-9520-43c5-ba77-58f1f022d982; Proxy: null)" (RequestToken: 7328c745-af5d-cd1b-a3e3-54dd56dcb268, HandlerErrorCode: HandlerInternalFailure)
```

### Reproduction Steps

Deploy this stack:

```ts
import { LoggingLevel, SlackChannelConfiguration, SlackChannelConfigurationProps } from 'aws-cdk-lib/aws-chatbot'

export class MyStack extends Stack {
  constructor(scope: Construct, id: string, properties: SlackChannelConfigurationProps) {
    super(scope, id)
    const { slackChannelId, slackWorkspaceId, slackChannelConfigurationName } = properties

    new SlackChannelConfiguration(this, 'SlackChannel', {
      slackChannelConfigurationName,
      slackWorkspaceId,
      slackChannelId,
      loggingLevel: LoggingLevel.INFO,
      logRetention: RetentionDays.ONE_MONTH,
    })
  }
}

```

### CDK CLI Version

2.143.0

### Framework Version

2.143.0

### Node.js Version

18.19.0

### OS

Linux

### Language

TypeScript

### Language Version

TypeScript (5.4.5)

**Comment by paulocen** [comment]
Update: Payload has changed to the AWSChatbot service. 
`Resource handler returned message: "Invalid request provided: Tag elements cannot contain whitespaces (Service: AWSChatbot; Status Code: 400; Error Code: InvalidRequestException; Request ID: bafe3797-61b0-4882-a3fd-8d0ee216dcfc; Proxy: null)" (RequestToken: df3c3e43-c259-2807-37f6-dc8b4b7d5622, HandlerErrorCode: InvalidRequest)`

**Comment by paulocen** [comment]
Seems resolved now @nguyentoanit ??

**Comment by nguyentoanit** [comment]
@paulocen : Not yet from my side. Still get the same error. 🤷 
How about you?

**Comment by moltar** [comment]
Nope, the issue still exists:

> Resource handler returned message: "An error occurred from the supplied tags: Unable to modify resource Tags. Please try again. (Service: WheatleyOrchestration; Status Code: 409; Error Code: ConflictException; Request ID: 0db9bdf5-11ba-4af9-932a-aee8e5a1d34a; Proxy: null)" (RequestToken: 99fd36c0-2cb5-0ca7-1fd8-53c636b5861f, HandlerErrorCode: HandlerInternalFailure)

![screenshot-20240610T210257-S7hXEF8l@2x](https://github.com/aws/aws-cdk/assets/491247/c771ec04-5829-439b-a652-25d01e1db1a6)

**Comment by moltar** [comment]
@paulocen Also, I am not sure what you mean by this:

> Payload has changed to the AWSChatbot service.

?

**Comment by moltar** [comment]
I think this is some internal error from AWS, because we are not even setting a tag on the given resource. I have inspected the actual CF template as it's in the CF stack.

Here's the definition:

```json
    "DriverSlackChannel8D461434": {
      "Type": "AWS::Chatbot::SlackChannelConfiguration",
      "Properties": {
        "ConfigurationName": "AD-OpsTools-foo",
        "IamRoleArn": {
          "Fn::GetAtt": [
            "DriverSlackChannelConfigurationRoleB1E5C93B",
            "Arn"
          ]
        },
        "LoggingLevel": "INFO",
        "SlackChannelId": "snipped",
        "SlackWorkspaceId": "snipped",
        "SnsTopicArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":sns:us-east-1:123:foo"
              ]
            ]
          },
          {
            "Fn::ImportValue": "..."
          },
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":sns:ap-northeast-1:123:foo"
              ]
            ]
          },
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":sns:me-central-1:123:foo"
              ]
            ]
          }
        ]
      }
    },
```

**Comment by khushail** [comment]
Hi @nguyentoanit , thanks for reaching out and sharing the repro code. I am not able to repro the error on my side rather, getting a different one which is related to channel access, seems fixable so working on it.

Meanwhile, as a workarond, Could you please try using the L1 construct like the given code shared below as I was able to successfully deploy the chatbot with L1 Construct . 

Source code -
```ts
    const slackChannel = new CfnSlackChannelConfiguration(this, 'SlackChannelConfiguration', {
      configurationName: "cdk-integration-test-slack-config",
      slackChannelId: "********12",
      slackWorkspaceId: "T0****Z",
      loggingLevel: LoggingLevel.ERROR,
      iamRoleArn: "arn:aws:iam::123456789:role/service-role/AWSChatbot-role-1503-private", 
    });
```

Generated Synth template snippet-

```
{
 "Resources": {
  "SlackChannelConfiguration": {
   "Type": "AWS::Chatbot::SlackChannelConfiguration",
   "Properties": {
    "ConfigurationName": "cdk-integration-test-slack-config",
    "IamRoleArn": "arn:aws:iam::123456789:role/service-role/AWSChatbot-role-1503-private",
    "LoggingLevel": "ERROR",
    "SlackChannelId": "********12",
    "SlackWorkspaceId": "T0****Z"
   },
   "Metadata": {
    "aws:cdk:path": "SlackissueStack/SlackChannelConfiguration"
   }
  },
  "CDKMetadata": {
   "Type": "AWS::CDK::Metadata",
   "Properties": {
    "Analytics": "v2:deflate64:H4sIAAAAAAAA/yXJOw6DMBBF0bXQ25MYUaT3DmAB0WAPYcAZS/4kRZS9Y0T1nu7pwQwD3Dv8Zu38rgPP8JsKul219HQrljkWsItMoUW7oggFG2XhV01YOIpqOFKONTk6f0PPJ/yVRE+w5dvHPMD0YLotM+tUpfCbYLz2AKlKzkyDAAAA"
   },
   "Metadata": {
    "aws:cdk:path": "SlackissueStack/CDKMetadata/Default"
   },
   "Condition": "CDKMetadataAvailable"
  }
 },
```

Deployment -

<img width="1006" alt="Screenshot 2024-06-10 at 6 27 29 PM" src="https://github.com/aws/aws-cdk/assets/117320115/5853c342-2ec3-41d9-8ddb-99fe474156ce">



Let me know if that works for you.

**Comment by moltar** [comment]
Why would L1 be any different?

It just produces the same CloudFormation template in the end.

**Comment by khushail** [comment]
yes, it would. I am not saying its wrong. Its just that deployment is successful so that would mean there is some bug in L2 construct implementation which I am currently investigating.

I shared the L1 construct as an alternate to existing issue.

**Comment by moltar** [comment]
I don't see how the L2 or L3 has anything to do with it. I posted the entire template. Which is ultimately what the pipeline deploys. Pipeline does _not_ use CDK to deploy. It uses CodePipeline native actions, and the templates produced by CDK. The template is there for everyone to see, as an artifact of the build. It does not even contain tags.

**Comment by nguyentoanit** [comment]
the AWS team has made some adjustments on their end.
And the issue seems to be resolved.
