### ISSUE TITLE
Make Alarm objects region-aware

### ISSUE THREAD

**Issue by ManuelVs** [aws/aws-cdk#5787]
### Description

Make available the creation of cross-region and cross-account aware Alarms. Recently commits made metrics region and account aware, but they will not be completed until those metrics can be used among Alarms, as a normal Metric.

### Use Case

I am creating dashboards with metrics available in other regions and accounts in my own AWS account, since I don't have access to the source account. I am automatizing the creation of this dashboards with AWS CDK (this tool), and I would like to automatize the creation of Alarms as well, based on cross account metrics.

### Proposed Solution

I don't know how to implement this, I would need to spend some time understanding the implementation to be able to provide a possible implementation. As far as I know, a proper implementation of [this cases](https://github.com/aws/aws-cdk/blame/master/packages/%40aws-cdk/aws-cloudwatch/lib/alarm.ts#L299-L304) should be done. The creation of this cross-account Alarms is very straight-forward. I think that it is only needed to specify the `accountId` and `region` parameters when rendering the alarm's metric.

### Other

When creating the Alarm based on a Metric

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I think you may be running into the issue that was fixed here: https://github.com/aws/aws-cdk/pull/5775

Is your Alarm in an env-agnostic stack?

**Comment by ManuelVs** [comment]
No, it is not. I specify the accountId and region for the stack on the `bin/blabla.ts` file. I did this so I don't have to wait for #5775 to be released on the next version of AWS CDK. Correct me if I am wrong, but will #5775 solve this issue? The error that I am getting is the following:

```
Cannot create an Alarm in account 'MY_ACCOUNT' based on metric 'METRIC' in 'OTHER_ACCOUNT'.
```

Thanks for your help!

**Comment by ManuelVs** [comment]
Hi! I have updated to AWS-CDK v1.21.0. I still have the following issues:

- If I **delete** the `account` and `region` `env` parameters of the stack (so I am running with an env-agnostic stack), the deployment works successfully but the alarm's metrics are not generated correctly. Again, the `accountId` and `region` parameters are not generated, similar as #5747.
- If I **specify** the `account` and `region` `env` parameters of the stack, I get the same error as explained above.

Thanks for your help!

**Comment by rix0rrr** [comment]
I misunderstood your question last time, sorry for that.

The issue is that CloudWatch does not support cross-account Alarms at all, so there is no way for us to create those. Sorry, nothing to be done at the moment.
