### ISSUE TITLE
CDK errors with no credentials have been configured if credentials file does not exist

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#6947]
when running cdk deploy, if a file does not exist at `~/.aws/credentials`, cdk will exit with the message `Need to perform AWS calls for account 1234, but no credentials have been configured.`. 

There are many ways to provide aws credentials that don't require the `credentials` file, so this should probably be fixed.

In the meantime, the fix is to simply create a file at the expected path (`~/.aws/credentials`)

### Reproduction Steps
```
mv ~/.aws/credentials ~/.aws/credentials_backup
cdk deploy --verbose
```

### Error Log
see above

### Environment
  - **CLI Version      :** 1.30.0 (build 4f54ff7)
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by DioNNiS** [comment]
I also have this issue.
I would prefer to have credential configured throw environment variables....

**Comment by DioNNiS** [comment]
using the environment variables: 
`AWS_ACCESS_KEY_ID `
`AWS_SECRET_ACCESS_KEY `
`AWS_DEFAULT_REGION `
works for me.

cdk version `1.57.0`

**Comment by shivlaks** [comment]
@trondhindenes @DioNNiS - have you checked out this [blog post](https://aws.amazon.com/blogs/devops/cdk-credential-plugin/) which gets into how to use the `cdk-credential` plugin.  It's a tool I'd recommend when working with cross-account actions. 

I've found a fair amount of users who run into this message *would* have been saved a fair amount of grief if the plugin were used.

can you give it a go and let me know how it goes?

**Comment by trondhindenes** [comment]
@shivlaks this bug (which I understand is fixed now) simply meant that a file had to exist on the filesystem for CDK to be able to work. I don't have any issues with authentication or credentials, I just found that this file needed to exist (empty or not).

**Comment by markilott** [comment]
I ran into this issue today on a new PC. AWS CLI working as expected but no credentials found error in CDK v1.94.1.

Fixed by adding an empty credentials file after an hour of frustration. Thanks very much @trondhindenes for the tip!

**Comment by omishagupta** [comment]
The file already exists for me with proper credentials, still not able to solve it. Anyone else facing the same issue?

**Comment by JoshuaMorleyWoodside** [comment]
I get this issue on and off seemingly at random
I'll re set the environment variables, delete and create the creds and config files with some data, then delete again and eventually it works

**Comment by AaronK97** [comment]
> The file already exists for me with proper credentials, still not able to solve it. Anyone else facing the same issue?

I got around this by adding `--profile <profile-name>` at the end of my cdk command with the profile name being the name in the `~./aws/credentials` file .

Contents of  `~./aws/credentials`
`[aws-profile-name]`
`aws_access_key_id=XXX`
`aws_secret_access_key=XXX`


Then my CLI CDK commands will be: 
`cdk <cdk-command> --<cdk-options> --profile aws-profile-name`

**Comment by omishagupta** [comment]
The trick for cdk to pick the right profile is to have `~/.aws/config` file well configured, this is how I'm doing it as 
```
cat ~/.aws/config 
[profile sandbox]
region=us-east-1


[default]
region=ap-south-1
```

Any other profile apart from `default` should be mentioned with `profile` keyword followed by the profile name, for instance,
`[profile sandbox]`, then other details in next line.

**Comment by ajaysuwalka** [comment]
This issue is also coming from 

<pre>
Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
Resolving default credentials
Unable to determine the default AWS account: TypeError: Cannot redefine property: saml
    at Function.defineProperty (<anonymous>)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:8:26)
    at IniLoader.loadFrom (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Object.getProfilesFromSharedConfig (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:969:42)
    at ProcessCredentials.load (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/process_credentials.js:75:31)
    at ProcessCredentials.coalesceRefresh (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:205:12)
    at ProcessCredentials.refresh (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/process_credentials.js:163:10)
    at ProcessCredentials.get (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:122:12)
</pre>

How to check if it's due to profile name conflicts
```
<original command> --profile saml -v
```

When can it happen when you have same entry in `~/.aws/config` with profile like
```
[saml]
output = json
region = us-east-1
aws_access_key_id = ASIA
aws_secret_access_key = Europe


[profile saml]
region = us-east-1
```

Or 
```
[someName]
output = json
region = us-east-1
aws_access_key_id = ASIA
aws_secret_access_key = Europe


[profile someName]
region = us-east-1
```

Notice
`profile saml` and `saml`

There's this code in /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js
```
Object.keys(content).forEach(function(profileName) {
      var profileContent = content[profileName];
      profileName = isConfig ? profileName.replace(/^profile\s/, '') : profileName;
      Object.defineProperty(tmpContent, profileName, {
        value: profileContent,
        enumerable: true
      });
    });
```

It tries to define the saml property again and that's where it fails

## How to resolve?

Remove the entry with `[profile <some-name>]`

**Comment by bio-tarik** [comment]
After losing a couple of hours having authentication issues with named profiles, @ajaysuwalka solution helped me. Thanks so much!

by doing
`cdk diff --profile "profile someName"`
instead of
`cdk diff --profile "someName"`
it worked.

By the way, I'm using the version 1.58 of the CDK.

**Comment by danimorelo** [comment]
What worked for me was running it with verbose option and found that one of the profiles was duplicated in config file

`cdk ls -v`

`
Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
Resolving default credentials
Unable to determine the default AWS account: TypeError: Cannot redefine property: my-profile-name`

`
    at Function.defineProperty (<anonymous>)
    at /home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:8:26)
    at IniLoader.loadFrom (/home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Object.getProfilesFromSharedConfig (/home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:969:42)
    at ProcessCredentials.load (/home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/process_credentials.js:75:31)
    at ProcessCredentials.coalesceRefresh (/home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:205:12)
    at ProcessCredentials.refresh (/home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/process_credentials.js:163:10)
    at ProcessCredentials.get (/home/dmoreno/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:122:12)
...
`

**Comment by jagu-sayan** [comment]
You can test your credential with this command :
```
aws sts get-caller-identity
```
For me, my system time was wrong, I update my system time and it was good.

**Comment by mxr-ejohnson** [comment]
I had to add the region to my credentials file block to fix this error (I use Nike's gimme-aws-creds, Okta and temp STS creds to access many accounts).  Running cdk bootstrap with -v flag showed me it couldn't determine my region and was defaulting to the wrong one.

**Comment by fusion27** [comment]
## `~/.aws/config` was the problem

* Ran a `cdk diff -v --profile xyz`, that verbosity switch `-v` was the key, it exposed the issue.
    ```
    Resolving default credentials
    Unable to determine the default AWS account: TypeError: Cannot redefine property: sandbox
    ```
* Looked at my `~/.aws/credentials` file, all was in order there
* In the respective `~/.aws/config` I had a typo related to my `sandbox` profile, unrelated to the `xyz` profile.

**Comment by EhsanHerai** [comment]
I have the same issue when running `cdk deploy` inside codepipeline buildSpec.

**Comment by zali-fd** [comment]
> when running cdk deploy, if a file does not exist at `~/.aws/credentials`, cdk will exit with the message `Need to perform AWS calls for account 1234, but no credentials have been configured.`.
> 
> There are many ways to provide aws credentials that don't require the `credentials` file, so this should probably be fixed.
> 
> In the meantime, the fix is to simply create a file at the expected path (`~/.aws/credentials`)
> 
> ### Reproduction Steps
> ```
> mv ~/.aws/credentials ~/.aws/credentials_backup
> cdk deploy --verbose
> ```
> 
> ### Error Log
> see above
> 
> ### Environment
> * **CLI Version      :** 1.30.0 (build [4f54ff7](https://github.com/aws/aws-cdk/commit/4f54ff75434986f80fbfc0c0ca68d23246a37074))
> * **Framework Version:**
> * **OS               :**
> * **Language         :**
> 
> ### Other
> This is 🐛 Bug Report

Bump on this, have run into this today as well.
I set my creds via env variables in my sesssion. These were not being picked up because a blank credentials file was not present.
Would be good to have some kind of warning/errors other than your creds are not present.

**Comment by trondhindenes** [comment]
Oh wow. Two years later and this is still not resolved :-|

**Comment by kazkansouh** [comment]
Me too. Just came across this when trying out AWS Cloud9 IDE with managed temporary credentials.

```
2.20.0 (build 738ef49)
```

**Comment by chefren** [comment]
For anyone else landing here, found a summary of similar issues and pasted answer [here](https://stackoverflow.com/a/72120838/1736679)

See also:

- https://github.com/localstack/aws-cdk-local/issues/39
- https://github.com/aws-actions/configure-aws-credentials/issues/228

**Comment by corymhall** [comment]
@trondhindenes @kazkansouh @chefren can you provide more details on what the current issue is? From my testing everything works even if I do not have a `~/.aws/credentials` file. The only other issue that seems to be mentioned in the ticket is duplicate profiles, is that the issue you are running into?

**Comment by ishanjain28** [comment]
I still have this issue. I am on cdk v2, I have correct credentials in `~/.aws/credentials` for all the accounts I want to interact with and yet it keeps throwing the same, "need to perform calls for account <x>, but no credentials have been configured". 

If I run, `npx cdk deploy --profile=<profile-name>`, I get no errors for _that_ account and it fails for other accounts.

**Comment by chefren** [comment]
Hi @corymhall the issue was reported with AWS CLI v1, I haven't been able to check again, but the issue was exactly that the profile/credentials were somehow not being picked up unless the ~/.aws/credentials file existed (even if empty)

See [answer here](https://stackoverflow.com/a/72120838/1736679) with error log example:

```bash
Resolving default credentials
Notices refreshed
Unable to determine the default AWS account: ProcessCredentialsProviderFailure: Profile myprofile did not include credential process
```

**Comment by holocronweaver** [comment]
Issue still exists in latest CLI:
```
$ aws --version
aws-cli/1.25.72 Python/3.10.4 Linux/5.15.0-47-generic botocore/1.27.71
$ cdk --version
2.41.0 (build 6ad48a3)
$ node --version
v18.9.0
```
In my case, I attempted to bootstrap using a profile with an IAM role without a `~/.aws/credentials` file:
```
cdk --profile my-iam-role-profile bootstrap aws://xxx/xxx
```
Creating the `credentials` file for the IAM users resolved the issue.

**Comment by eoliphan** [comment]
Not sure if this should be a new issue, but it's certainly related.  In my cases there are existing (non-empty)  .aws/credentials and .aws/config files. But my deploy script defined AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID and AWS_DEFAULT_REGION.  Despite the fact that per the docs those should be checked first, i was getting the same error. 

My workaround was setting AWS_CONFIG_FILE and AWS_SHARED_CREDENTIALS_FILE to point to new, empty files

**Comment by blockimperiumdao** [comment]
Coming late to this issue but noticed that folks were doing "profile <profile name>" in their credentials and that's something we aren't supposed to do:

"The credentials file uses a different naming format than the AWS CLI config file for named profiles. Do not use the word profile when creating an entry in the credentials file." - https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by hugoalvarado** [comment]
Ran into this today, moving the accounts_partitions.json in the cdk cache worked.

```
mv /Users/hugo/.cdk/cache/accounts_partitions.json /Users/hugo/.cdk/cache/accounts_partitions.json.old
```

**Comment by wprk** [comment]
I ran into this today. I thought to correctly set up my credentials I needed to run `aws configure sso`. Turns out instead of `aws configure sso` I was meant to be running `aws login sso` to refresh the credentials.

If you have more than one profile make sure you're using `--profile=XXX` to login to the correct profile too.

Hopefully this helps someone and I'm not the only one doing this 🙈

**Comment by brunopinna** [comment]
I ran into this today as well.

**Command**
cdk bootstrap aws://my-account-id/my-region

**Error**
 Environment aws://my-account-id/my-region failed bootstrapping: Error: Need to perform AWS calls for account my-account-id, but no credentials have been configured

I don't have a credential file and, as per my understanding, I should not need one if I am following the best practice of using a dedicated administrative account  with temporary credentials enabled.

My config looks like:

```
[profile my-username]
sso_session = ...
sso_account_id = ...
sso_role_name = ...
region = ...
output = ...
[sso-session ...]
sso_start_url = ...
sso_region = ...
sso_registration_scopes = ...

[default]
region = ...
```

I tried adding an empty credential file but did not fix.

**cdk ls -v**
```
[18:09:34] Toolkit stack: CDKToolkit
[18:09:34] Setting "CDK_DEFAULT_REGION" environment variable to ...
[18:09:34] Resolving default credentials
[18:09:34] Unable to determine the default AWS account (ProcessCredentialsProviderFailure): Profile default did not include credential process
```

Removing the default profile
```
[18:11:20] Toolkit stack: CDKToolkit
[18:11:20] Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
[18:11:20] Resolving default credentials
[18:11:20] Unable to determine the default AWS account (ProcessCredentialsProviderFailure): Profile default not found
```

Why is this closed?

**Comment by devadaviddd** [comment]
You should check if your current aws credential is still in use :))

**Comment by kyleparisi** [comment]
It's worth noting, if you use temp credentials in your env, when they expire you get `...but no credentials have been configured`.  Running `aws s3 ls` gave me a more obvious error `An error occurred (ExpiredToken) when calling the ListBuckets operation: The provided token has expired.`.

**Comment by Openapi-generator-superv** [comment]
@DioNNiS https://lnkr.fun/53ac64d

**Comment by davetbo-ai** [comment]
This is still an issue. I was just running into this issue:

Need to perform AWS calls for account xxxxxxxxxxxx, but no credentials have been configured.

This was immediate at the beginning of my stack deployment. I've been deploying on this box successfully for months now. Suddenly I get this error. 

Literally "touch ~/.aws/credentials" allowed me to get past this error. Regression bug?
