### ISSUE TITLE
CDK Code Pipeline Lambda deployment is deleting old versions with removal policy set to RETAIN

### ISSUE THREAD

**Issue by zachbarrow** [aws/aws-cdk#7636]
After following the guide for a [Lambda deploying pipeline](https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html), I eventually got a running build. I can commit a change to codecommit which will kick off the pipeline. The specified alias will be moved (or created) and point to the new version. But the old version and any alias attached to it will be deleted. I am always left with two versions ($LATEST and the just-deployed one) and one alias (the just-deployed one).

What I expected to happen in the case of a commit that does not change the alias:
- The alias is updated to point to the new version and the old version is **not** deleted

What I expected to happen in the case of a commit that did change the alias:
- The previous alias(es) points to whatever version they were pointing to before
- The new alias points to the new version and any old versions are **not** deleted

### Reproduction Steps

1. Follow this [guide](https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html)
2. Change the `FunctionProps.currentVersionOptions.removalPolicy` to `RETAIN`. (this actually does not appear to matter)
3. Change the name of the alias and commit.
4. The deployment deletes the previous version and alias and sets the new alias to the new version.

```
    this.lambdaCode = Lambda.Code.fromCfnParameters();
    const lambdaFnProps: Lambda.FunctionProps = {
      handler: "index.handler",
      code: this.lambdaCode,
      runtime: Lambda.Runtime.NODEJS_12_X,
      description: "description",
      role: role,
      functionName: this.lambdaFnName,
      currentVersionOptions: {
        removalPolicy: RemovalPolicy.RETAIN
      }
    };

    const func = new Lambda.Function(this, "LambdaFunction", lambdaFnProps);
    const version = func.addVersion(new Date().toISOString());
    const alias = new Lambda.Alias(this, 'LambdaAlias', {
      aliasName: 'dev2',
      version,
    });

    const deploy = new CodeDeploy.LambdaDeploymentGroup(this, "LambdaDeploymentGroup", {
      alias: alias,
      deploymentConfig: CodeDeploy.LambdaDeploymentConfig.ALL_AT_ONCE,
    });
```

### CDK Diff Output

The output from running cdk diff pretty much shows what ends up happening:

```
Resources
[-] AWS::Lambda::Version LambdaFunctionVersion20200428T062510953Z1CA2012F destroy
[-] AWS::Lambda::Alias LambdaFunctionVersion20200428T062510953ZAliasdev26C46D216 destroy
[+] AWS::Lambda::Version LambdaFunction/Version2020-04-28T06:39:18.760Z LambdaFunctionVersion20200428T063918760Z149463F3 
[+] AWS::Lambda::Alias LambdaFunction/Version2020-04-28T06:39:18.760Z/Aliasdev2 LambdaFunctionVersion20200428T063918760ZAliasdev282DEF3AB 
```

### Environment

  - **CDK Version: 1.35**
  - **OS: Mac**
  - **Language : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
I am retaining old versions like this: https://github.com/taimos/cdk-construct-alexa-skill/blob/master/lib/alexa-stack.ts#L71

**Comment by zachbarrow** [comment]
> I am retaining old versions like this: https://github.com/taimos/cdk-construct-alexa-skill/blob/master/lib/alexa-stack.ts#L71

Thanks @hoegertn but it I am getting a 404.

**Comment by hoegertn** [comment]
Sorry, I forgot to make the repo public after the release. I fixed it.

**Comment by zachbarrow** [comment]
I have tried to simplify this down to see if I could get the results I wanted. I have had partial success but aliases are still getting destroyed. My simplified approach completely cuts any pipeline from the picture. I am deploying directly from my terminal and building a zip file every time I run the CDK script. What is happening in this case is, for every run, a new function version is deployed and whatever alias I have specified is applied to it. The old version is orphaned and not deleted, but the old alias is destroyed.

### Simplified Code

```  
const lambdaFnProps: Lambda.FunctionProps = {
      handler: "index.handler",
      code: new Lambda.AssetCode(zipFile),
      runtime: Lambda.Runtime.NODEJS_12_X,
      description: "description",
      role: role,
      functionName: this.lambdaFnName,
      currentVersionOptions: {
        removalPolicy: RemovalPolicy.RETAIN
      },
      logRetention: Logs.RetentionDays.TWO_WEEKS
    };

    const func = new Lambda.Function(this, "LambdaFunction", lambdaFnProps);
    const currentVersion = func.currentVersion;
    const alias = currentVersion.addAlias("dev");
```

### CDK Diff Output

```
Resources
[-] AWS::Lambda::Version LambdaFunctionCurrentVersion7D5C86E3900cb27646e1c39df313ce2faee97972 orphan
[-] AWS::Lambda::Alias LambdaFunctionCurrentVersionAliasdev3D641B549 destroy
[+] AWS::Lambda::Version LambdaFunction/CurrentVersion LambdaFunctionCurrentVersion7D5C86E3c8a8980823169e80fcc3d03f4983b112 
[+] AWS::Lambda::Alias LambdaFunction/CurrentVersion/Aliasdev2 LambdaFunctionCurrentVersionAliasdev2AB2F0098 
[~] AWS::Lambda::Function LambdaFunction LambdaFunctionBF21E41F 
...
```

**Comment by zachbarrow** [comment]
I have come up with a work around that involves completely separating the Lambda stack from an "Aliases" stack. I create the Lambda. External to that I set up a stack of aliases and lookup the function version I need by ARN via configuration and adjust the aliases accordingly. This allows me to move aliases around as necessary. But, it was not very intuitive figuring this out. My solution followed the general approach:

```
const function = Function.fromFunctionArn(...);
const version = Version.fromVersionAttributes(..., {lambda: function});
const alias = new Alias(...,{version});
```

**Comment by skinny85** [comment]
@zachbarrow ,

thanks for opening the issue. Your problem is with this line:

```ts
    const version = func.addVersion(new Date().toISOString());
    const alias = new Alias(...,{version});
```

This creates a new version each time the code is executed, and of course deletes the old one as well.

If you want to retain the previous version, you can instead use a specific string there. So, you would start with this:

```ts
    const version = func.addVersion('Version1');
    const alias = new Alias(...,{version});
```

And, when doing a change, you would change that to:

```ts
    // old version
    func.addVersion('Version1');
    // new version
    const version = func.addVersion('Version2');
    const alias = new Alias(...,{version});
```

Hope this helps!

Thanks,
Adam

**Comment by zachbarrow** [comment]
@skinny85 I thought that "random" version string was necessary for the Cloud Formation aspect from the guide to work right. I was operating under the assumption that `addVersion` would add versions, but not delete them 🤯. I see the logic of it now but it was not obvious to me at the time. I will test it and update whether I get the results I was expecting.

**Comment by skinny85** [comment]
@zachbarrow the "random" part was just to ensure that you don't forget to do it on every change. With the method I've shown you, if you update your Lambda code, but don't create a new `Version` (with ID `'Version3'`, to continue the example), your Lambda code changes will not be reflected! (Because Versions are immutable in Lambda).

The fact the previous Version is deleted is just standard CDK semantics, I thought it would be obvious. For example, if you have:

```ts
new s3.Bucket(this, 'Bucket1');
```

And if you change it to:

```ts
new s3.Bucket(this, 'Bucket2');
```

The behavior will be:

1. A completely new Bucket, with a new physical name, will be created.
2. The old Bucket, with logical ID `Bucket1`, will be deleted.

Exactly the same thing happens with the `Version`, it's only harder to see perhaps, because we always generate a different ID :).

More info here: https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html#identifiers_logical_ids

Thanks,
Adam

**Comment by zachbarrow** [comment]
@skinny85 I did some testing and your suggestions worked. Thanks for the help. Thanks also @hoegertn for the code example.
