### ISSUE TITLE
[certificate manager] DnsValidatedCertificate deployment fails in cn-north-1 region

### ISSUE THREAD

**Issue by mmajis** [aws/aws-cdk#8697]
### The Question

I'm trying to create a DNS validated certificate in cn-north-1. Running `cdk deploy` fails with `Failed to create resource. Credential should be scoped to a valid region, not 'cn-north-1'.`

Snippet from `cdk deploy -v` output:

```
 4/6 | 12:04:17 PM | CREATE_FAILED        | AWS::CloudFormation::CustomResource | DomainAndCert/StarCert/CertificateRequestorResource/Default (DomainAndCertStarCertCertificateRequestorResource543B058B) Failed to create resource. Credential should be scoped to a valid region, not 'cn-north-1'. 
	new CustomResource (/Users/mika/cdkissue/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
	\_ new DnsValidatedCertificate (/Users/mika/cdkissue/node_modules/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts:96:25)
```
Code: 

```
this.starCertificate = new certmgr.DnsValidatedCertificate(this, "StarCert", {
    domainName: `*.${props.publicDomainName}`,
    hostedZone: this.publicHostedZone,
    route53Endpoint: props.route53Endpoint //this is needed for route53 China
});
```

Looking at the logs for the custom resource lambda, it seems to be an issue with upserting Route53 records to validate the cert:

```
2020-06-23T09:01:07.924Z	c952e3b2-68f5-4ba1-8599-be55491da456	INFO	Upserting 1 DNS records into zone REDACTED:
2020-06-23T09:01:07.925Z	c952e3b2-68f5-4ba1-8599-be55491da456	INFO	_4492e8f244dab126a5c78dfd7401d1cf.my-redacted-domain.com. CNAME _801b667a2cee8c547d6831e61e2884d7.kfpsnxvjp.acm-validations.amazonaws.cn.
2020-06-23T09:01:08.142Z	c952e3b2-68f5-4ba1-8599-be55491da456	INFO	Caught error SignatureDoesNotMatch: Credential should be scoped to a valid region, not 'cn-north-1'. . Uploading FAILED message to S3.
```

### Environment

  - **CDK CLI Version:** 1.46.0 
  - **Module Version:** 1.46.0 
  - **Node.js Version:** v12.16.1 
  - **OS:** MacOS Catalina 
  - **Language:** TypeScript 

### Other information

Could be related to https://github.com/aws/aws-sdk-js/pull/3274. Not sure what version of `aws-sdk-js` the cert validation custom resource lambda is running.

**Comment by zxkane** [comment]
It's same as IAM endpoint issue(https://github.com/aws/aws-cdk/issues/8185#issuecomment-645189298) in region `cn-northwest-1`. 

The JS SDK has fixed the endpoint issue, but the lambda nodejs runtime still does not pick up the latest version yet.

**Comment by zxkane** [comment]
Due to you explicitly specify the route53 endpoint in `DnsValidatedCertificate`, it should use correct endpoint in that [verification lambda](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L83).

I did a try in `cn-northwest-1` region, it failed on the timeout to verify the certification issued in ACM.

```typescript
certificate = new certmgr.DnsValidatedCertificate(this, 'Certificate-' + domainName, {
        domainName,
        hostedZone,
        region: this.region,
        validationDomains: {
          targetHost: domainName
        },
        validationMethod: certmgr.ValidationMethod.DNS,
        route53Endpoint: stack.region.startsWith('cn-') ? 'route53.amazonaws.com.cn' : undefined,
      });
```

Below is log of lambda,
```

17:57:10
2020-06-24T09:57:10.156Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO Requesting certificate for nexus.testtest.vme360.com

17:57:11
2020-06-24T09:57:11.019Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO Certificate ARN: arn:aws-cn:acm:cn-northwest-1:account-id:certificate/27273476-faa6-46b0-ad9f-bdf0d3025c24

17:57:11
2020-06-24T09:57:11.019Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO Waiting for ACM to provide DNS records for validation...

17:57:15
2020-06-24T09:57:15.633Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO Upserting 1 DNS records into zone Z2C5FOBW37XAO3:

17:57:15
2020-06-24T09:57:15.633Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO _8a25fabcdf9a5c0764813968ae8cb226.nexus.testtest.vme360.com. CNAME _b75ca6a5e1f0f5fe9564dd4aca0877fe.kfpsnxvjp.acm-validations.amazonaws.cn.

17:57:16
2020-06-24T09:57:16.140Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO Waiting for DNS records to commit...

17:57:46
2020-06-24T09:57:46.762Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO Waiting for validation...

18:07:23
2020-06-24T10:07:23.442Z 19a1dc67-3e26-488a-8b18-4a85e9c921a2 INFO Caught error ResourceNotReady: Resource is not in the state certificateValidated. Uploading FAILED message to S3.

18:07:23
END RequestId: 19a1dc67-3e26-488a-8b18-4a85e9c921a2
```

**Comment by skinny85** [comment]
Hello @mmajis ,

thanks for opening the issue. Does @zxkane 's response here: https://github.com/aws/aws-cdk/issues/8697#issuecomment-648764918 solve your problem?

Thanks,
Adam

**Comment by zxkane** [comment]
I do reproduce it with same error in region cn-north-1, it's related to route53 as global service misconfigured in built-in aws-sdk of lambda. The issue should be resolved after aws-sdk of lambda runtime is updated with pr mentioned above.

**Comment by mmajis** [comment]
Specifying the endpoint as suggested in https://github.com/aws/aws-cdk/issues/8697#issuecomment-648764918 does not resolve the issue. 

I believe the aws-sdk update of lambda runtime will fix this as @zxkane suggests.

**Comment by zxkane** [comment]
The lambda team is working on updating aws sdk for nodejs runtime. It'd better keeping the issue opening until it's validated.

**Comment by njlynch** [comment]
The SDK for NodeJS appears to be updated now; I can verify the CN Route53 endpoint is now accessible. This should unblock the above; please re-open if that's not the case.
